### ISSUE TITLE
build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values

### ISSUE THREAD

**Issue by mflint** [CocoaPods/Xcodeproj#113]
Xcodeproj 0.14.0
cocoapods 0.27.1

Everything was working fine until I added a third build configuration called "Screenshots". (Previously there were just the defaults, "Debug" and "Release")

Now when I re-run "pod update" or "pod install" I see this error:

`RuntimeError - [Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values: `{"Release"=>"6.0", "Debug"=>"6.0", "Screenshots"=>"4.3"}`
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.14.0/lib/xcodeproj/project/object/native_target.rb:82:in `common_resolved_build_setting'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.14.0/lib/xcodeproj/project/object/native_target.rb:113:in `deployment_target'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.14.0/lib/xcodeproj/project/object/native_target.rb:149:in `add_build_configuration'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/target_installer.rb:47:in `block in add_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/target_installer.rb:46:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/target_installer.rb:46:in `add_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:15:in `block in install!'`

This is weird. There is no mention of "4.3" anywhere in the `pbxproj` file.

Here's the "git diff" output (slightly abridged, but it does show the new configuration has deployment target 6.0 for each target):

```
diff --git a/SecretSquirrel.xcodeproj/project.pbxproj b/SecretSquirrel.xcodeproj/project.pbxproj
index 0ddaa4d..0ae74ec 100644
--- a/SecretSquirrel.xcodeproj/project.pbxproj
+++ b/SecretSquirrel.xcodeproj/project.pbxproj
@@ -4046,6 +4046,123 @@
            };  
            name = Release;
        };  
+       34EB211A18243704007E6362 /* Screenshots */ = {
+           isa = XCBuildConfiguration;
+           buildSettings = {
+               ....
+               IPHONEOS_DEPLOYMENT_TARGET = 6.0;
+               ....
+           };
+           name = Screenshots;
+       };
+       34EB211B18243704007E6362 /* Screenshots */ = {
+           isa = XCBuildConfiguration;
+           baseConfigurationReference = D5BCB7552C864FC390A8E50B /* Pods-SecretSquirrel.xcconfig */;
+           buildSettings = {
+               ....
+               IPHONEOS_DEPLOYMENT_TARGET = 6.0;
+               ....
+           };
+           name = Screenshots;
+       };
+       34EB211C18243704007E6362 /* Screenshots */ = {
+           isa = XCBuildConfiguration;
+           baseConfigurationReference = 2A0D4457AB5B40B28692352E /* Pods-SecretSquirrel Beta.xcconfig */;
+           buildSettings = {
+               ....
+               IPHONEOS_DEPLOYMENT_TARGET = 6.0;
+               ....
+           };
+           name = Screenshots;
+       };
 /* End XCBuildConfiguration section */
```

So that looks fine.

I can only assume that the inconsistency is in the _generated_ xcode project for cocoapods, rather than in the xcode project for my app.

This may also be relevant:

```
   CocoaPods : 0.27.1
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
    RubyGems : 2.0.3
        Host : Mac OS X 10.9 (13A603)
       Xcode : 5.0.1 (5A2053)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7cc542296b492be14e8d398ab32f099fae545575
```

Any suggestions gratefully received!

**Comment by jsuder** [comment]
Same here:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'MBXMapKit'

target 'ZoomerTests', exclusive: true do
  platform :ios, '8.0'
  pod 'Quick'
  pod 'Nimble'
end
```

Error:
```
RuntimeError - [Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values: `{"Release"=>"8.0", "Debug"=>"8.0", "Debug (live)"=>"7.0", "Release (staging)"=>"7.0", "Release (live)"=>"7.0"}`
```

(v. 0.36.0.beta.1)

**Comment by neonichu** [comment]
This should be fixed by #229

**Comment by jsuder** [comment]
Yup, it works now, thanks.

**Comment by tanmoy27112000** [comment]
if you have uncommented the ios version in podfile just comment it back
