### ISSUE TITLE
Saving a workspace breaks a workspace using containers

### ISSUE THREAD

**Issue by kylef** [CocoaPods/Xcodeproj#118]
As you can see in the following diff:

``` diff
    <FileRef
-      location = "container:GCE.xcodeproj">
+      location = "group:container:GCE.xcodeproj">
    </FileRef>
```

The original `container:GCE.xcodeproj` gets replaced by `group:container:GCE.xcodeproj`. I simply used `pod install` on this workspace and this happened.

**Comment by Sharonfx** [comment]
https://github.com/CocoaPods/Xcodeproj/pull/150 open
