### ISSUE TITLE
remove script build phase

### ISSUE THREAD

**Issue by jcavar** [CocoaPods/Xcodeproj#154]
Hi,
We have new_shell_script_build_phase method, but is it possible to remove shell script build phase once when it is added?

**Comment by pe-johndpope** [comment]
I manually ticked 'for installs only' and things progressed for now
 <img width="919" alt="Screen Shot 2022-02-26 at 1 39 20 am" src="https://user-images.githubusercontent.com/99936109/155733950-7dd9506a-e2cf-4759-9752-4d048600f155.png">
