### ISSUE TITLE
How to delete a file reference in Xcode project?

### ISSUE THREAD

**Issue by laiyierjiangsu** [CocoaPods/Xcodeproj#156]
Hi, 
  if i want to add a file reference to the xcode project ,i use add_file_references .
but if i want to delete a file reference in xcode project , how can i do ???

**Comment by thhmoc67** [comment]
> `Project::Object#remove_from_project` is the method you are looking after iirc.

@fabiopelosin can you explain how can i do it?

**Comment by SenthilmuruganAmudha** [comment]
> `Project::Object#remove_from_project` is the method you are looking after iirc.

can you explain with sample
