### ISSUE TITLE
Deterministic UUIDs

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/Xcodeproj#175]
I have been thinking about doing something similar to this for a while and the [xUnique](https://github.com/truebit/xUnique) revived my interest on this feature.

##### Context

The algorithm used by Xcode to generate UUIDs is not known. Xcodeproj currently has a conservative approach at tries to make UUIDs which are similar to those generated by Xcodeproj while checking if a duplicate already exists in the project before using a new one. A duplicate UUID would corrupt the project.

[xUnique](https://github.com/truebit/xUnique) proves that Xcode accepts UUIDs regardless of the length and of the type.

##### Proposal

- Generate longer UUIDs
- Derive the UUID from a hash of the attributes of the new objects and the UUID of the parents. This would greatly reduce the noise when recreating a project from scratch.
- Add a subcommand to “normalize” projects.

##### Alternative

- Prefix UUIDs with a string to namespace the ones generated by Xcodeproj and avoid the need to check for collisions.
- Use a hash of the timestamp for the UUIDs.

**Comment by mrousavy** [comment]
I think I'm experiencing an issue with deterministic UUIDs [here](https://github.com/CocoaPods/CocoaPods/issues/10506), does anyone have an idea what might be wrong here?
