### ISSUE TITLE
Add entire folder to xcodeproj

### ISSUE THREAD

**Issue by swl367** [CocoaPods/Xcodeproj#178]
I understand we can add individual files to the target and add file references to those files, but can we do this in one step for an entire folder at some absolute path? (Of course there would need to be some way of knowing which files are .m files and which are .h)

e.g.

require 'xcodeproj'
project_file = 'app.xcodeproj'
project = Xcodeproj::Project.open(project_file)

kit_group = project.new_group('UIKIT')
files = kit_group.new_files('absolute/path/to/my/files')

main_target = project.targets.first
main_target.add_file_references([files])

project.save(project_file)

**Comment by revolter** [comment]
The current link is: https://github.com/CocoaPods/CocoaPods/blob/377d9cdf4b542e7762fe833e01817a9e423edb34/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb#L77-L85
