### ISSUE TITLE
Explore the use of fiddle to save ASCII plists using Xcode frameworks

### ISSUE THREAD

**Issue by kylef** [CocoaPods/Xcodeproj#199]
We should be able to load `DVTFoundation.framework` dynamically using fiddle in Ruby which would allow us to save ASCII plists using the private API if available and Xcode is installed.

This provides a couple of benefits:

- No need to compile and install xcproj, this would be the standard behaviour of Xcodeproj.
- Removes the need to re-compile xcproj when Xcode changes.

Certainly not for the upcoming release. But I think in theory this could work and it would be great it we can get it to work.

/cc @alloy @0xced

**Comment by kballard** [comment]
As predicted, after installing Xcode 7, CocoaPods is now crashing when trying to call the private APIs in Xcode's private frameworks. See CocoaPods/CocoaPods#4151.
