### ISSUE TITLE
Group.find_subpath returns PBXFileReference

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/Xcodeproj#219]
I am creating a gem that allows you to create a project file from a simple DSL. As part of this you can include source files, frameworks and resources.

These are added as files and to the relevant build phases. It also creates groups that match the folder hierarchy of the file system.

I have an issue with bundles i.e .framework, .xcassets.

These are obviously added as files as xcode treats them that way and thats what we need to do to use them but to the ruby system they are also folders so Dir.Glob also returns the files inside them.

So my tool tries to add the headers to the xcodeproject. But since the bundle for these files has already been added as a file, any attempts to use find_subpath to create a group for the bundle folder causes a PBXFileReference to be returned, instead of a Group or nil (if it couldn't be created).

How would I solve this issue ? Is there a way to check if a file is already part of a bundle thats been added ?

**Comment by sergeyzenchenko** [comment]
@jcampbell05 any luck with adding .xcassets ?

**Comment by jcampbell05** [comment]
@sergeyzenchenko I found a way in the end where I use `mdls` to list out the metadata for the file. I'm still building it out, but essentially depending on the output my tool then figures out which phase to add the file to (as well as things as ignoring the files inside of a framework). 

Thank you for forking though, will keep you updated. I'm close to releasing something.
