### ISSUE TITLE
(Frameworks):  set Header Target Membership 'type' to Public || Private || Project

### ISSUE THREAD

**Issue by sstadelman** [CocoaPods/Xcodeproj#222]
I am trying to set the Target Membership 'type' to Public, for headers which should be made public in an iOS Framework.  I have a script which adds classes to the project and target, and I can successfully build and utilize the framework classes, after switching this value manually.

This may be currently possible via the [PBXBuildFile](http://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/PBXBuildFile#settings-instance_method) `#settings` instance attribute, but I don't see the (seemingly) correct values taking effect.

The Xcode UI shortcut is located here.  Note that I've already switched the value from "Project" to "Public" on the Booking.h class".
![image](https://cloud.githubusercontent.com/assets/377404/5446993/eb9bc93c-847b-11e4-8ab9-9823cf9bc9bd.png)

This is logically equivalent to moving the headers between the "Project" (default), "Private", and "Public" sections in the Target > Build Phases > Headers menu.
![image](https://cloud.githubusercontent.com/assets/377404/5447017/5f6d63d4-847c-11e4-8fb0-b1ff31a4687b.png)

I've been trying to use the PBXBuildFile and PBXHeaderBuildPhase to set this value, with no success, as follows:

``` ruby
for i in 0..target.headers_build_phase.files.length - 1
    build_file = target.headers_build_phase.files[i]
    build_file.settings = { 'Attributes' => ['Public']}
    logger.info build_file.pretty_print
end
```

outputs:

```
INFO  : <Hash> {"Booking.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Carrier.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Flight.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Flight_DQ.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Notification.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Subscription.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Travelagency.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"Travelagency_DQ.h"=>{"Attributes"=>["Public"]}}
INFO  : <Hash> {"ODataModel.h"=>{"Attributes"=>["Public"]}}
```

I've also tried initializing the PBXBuildFile directly on the Project + PBXFileReference, but do not see a method for adding it to the target references.

``` ruby
ref = classes_group.files[i]
if ref.last_known_file_type == 'sourcecode.c.h'
    reusable_build_settings = Xcodeproj::Project::PBXBuildFile.new(ref, { 'Attributes' => 'Public'})
end
target.add_file_references([ref])
```

It seems that the API for this value _should_ be on PBXFileReference, or PBXBuildFile.  Does anyone know if this is available?

**Comment by revolter** [comment]
Couldn't `PBXHeadersBuildPhase` overwrite the `add_file_reference` method to add a `visibility` parameter so you could do:

```ruby
framework_target.headers_build_phase.add_file_reference(file_reference, 'Public')
```

?

**Comment by emysa341** [comment]
For me the following script worked posted by @sstadelman , I changed 'Attributes' -> 'ATTRIBUTES'

`for i in 0..proj.objects.length - 1
    obj = proj.objects[i]
    if obj.class == Xcodeproj::Project::PBXBuildFile
        build_file = obj;
        build_file.settings = { 'ATTRIBUTES' => ['Public']}
        proj.save
    end
    logger.info obj.uuid
    logger.debug obj.pretty_print
end`
