### ISSUE TITLE
Codesigning issues with xcodebuild from xcodeproj made .xcodeproj

### ISSUE THREAD

**Issue by fxfactorial** [CocoaPods/Xcodeproj#226]
I'm trying to create an .xcodeproj from scratch but running into issues during building. 

I create the xcodeproj directory with 

    require 'xcodeproj'
    proj = Xcodeproj::Project.new('PictureNotes.xcodeproj')
    app_target = proj.new_target(:application, 'PictureNotes', :ios, '8.1')
    app_target.add_file_references([proj.main_group.new_file('main.m')])
    proj.save()

and then I try calling xcodebuild like so:
    ```xcodebuild -configuration Debug -sdk iphoneos8.1```

at which point I get the error:

    Check dependencies
    CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'

    ** BUILD FAILED **

    The following build commands failed:
	    Check dependencies
    (1 failure)

**Comment by kylef** [comment]
@fxfactorial You will need to configure code signing certificates and provisioning profiles to build to an iOS device. Unless you are targeting the simulator and not a device, which can be achieved by the following (using the iphonesimulator SDK):

```
xcodebuild -sdk iphonesimulator
```
