### ISSUE TITLE
Cocoapods prompting to report a bug when .xcodeproj is in a merge conflict 

### ISSUE THREAD

**Issue by sebastiangrail** [CocoaPods/Xcodeproj#238]
When the `.xcodeproj` file is in a merge conflict, running `pod update` or `pod install` results in cocoapods failing and showing the error reporting markdown template.

A better error message would be something like: "path/to/project.xcodeproj" is in a merge conflict. Resolve the conflict before running pod install/update"

**Comment by AliSoftware** [comment]
Wasn't it solved with #192 ?

Could you tell us what version of CocoaPods and XcodeProj are you using? (`pod --version` and `xcodeproj --version`)

**Comment by sebastiangrail** [comment]
```
> pod --version
0.35.0
> xcodeproj --version
0.20.2
```

`xcodeproj` seems to handle the merge conflict, but cocoapods then spits out an error reporting template, which I think is confusing, especially since it is known that the error is a merge conflict in the project file and not a bug in Cocoapods.

I originally reported the bug on the main Cocoapods repository at https://github.com/CocoaPods/CocoaPods/issues/3115 and was asked to report it here instead.

**Comment by kylef** [comment]
@sebastiangrail Thanks for reporting, it does actually belong in in CocoaPods. I've moved it to https://github.com/CocoaPods/CocoaPods/issues/3158.
