### ISSUE TITLE
new_file does not handle adding new ".framework" libraries

### ISSUE THREAD

**Issue by swl367** [CocoaPods/Xcodeproj#249]
I'm currently trying to add the GoogleMobileAds.framework library to my xcode project using the following code, but it's only adding the framework as a PBXFileReference. What I actually want is to also add it as a PBXBuildFile and to include it in the xcode project's Linked Libraries.

This is my ruby script:

```ruby
if (lastpath.include? ".framework")
	created_group = current_group.new_file(lastpath)
	main_target.add_file_references([created_group])
	external_add_array.push(created_group)
else
	created_group = current_group.new_group(lastpath);
	external_add_array.push(created_group)
	addfiles("#{item}/*", created_group, main_target, false)
end
```

Am I missing something here? Adding a .framework as a new_group is also wrong because it becomes a plain folder instead of a .framework.

**Comment by AliSoftware** [comment]
`add_file_references` does just that, adding the file to the project. It does not add the file to any particular target or build phase, so you should also tell which build phase you want to add your file to.

See methods on [AbstractTarget](http://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/AbstractTarget) and [NativeTarget](http://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/PBXNativeTarget) e.g. you could access `main_target. frameworks_build_phases` and `add_file_reference(file_ref, true)`, etc (That's just pointers gathered from the doc, I haven't tried it so feel free to try and adjust)

**Comment by swl367** [comment]
@AliSoftware Thanks a lot for the help. That definitely worked.

add_file_references was adding it into the wrong phase, so I did the following:

if (lastpath.include? ".framework")
	created_group = current_group.new_file(lastpath)
	main_target.frameworks_build_phases.add_file_reference(created_group, true)
	external_add_array.push(created_group)
else
	created_group = current_group.new_group(lastpath);
	external_add_array.push(created_group)
	addfiles("#{item}/*", created_group, main_target, false)
end

So now, my frameworks file is added to the project, as well as into the frameworks build phase.
