### ISSUE TITLE
Incorrect assumption about the value of `xco

### ISSUE THREAD

**Issue by kylef** [CocoaPods/Xcodeproj#257]
We have an incorrect assumption about the value of `xcode-select -p`, by curiosity I ran the command from @neonichu on https://github.com/CocoaPods/CocoaPods/issues/3312#issuecomment-85945668. I was faced by an error:

```
$ nm -g "`xcode-select -p`/../PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore"|grep PBXProject|wc -l
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: can't open file: `xcode-select -p`/../PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore (No such file or directory)
```

Note, this is effectively the cleanest OS X installation I have, I've never ran `xcode-select --select` on this machine, it has the absolute default value.

This result made it pretty clear we have some *incorrect* assumption that the result of `xcode-select -p`. By default it will return `/Applications/Xcode.app/Contents/Developer`, the Developer directory (note, this is what it should return according to `xcode-select --help`:

```
-p, --print-path            print the path of the active developer directory
```

It appears that everyone (myself included on my main system) has either manually changed it from the default, or never noticed or cared that XML plists were saved. Xcodeproj expects the value to be something like: `/Applications/Xcode.app/Contents`.

We should determine if there is a trailing `Developer` and remove it from out search for frameworks: https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/plist_helper.rb#L633

**Comment by neonichu** [comment]
I don't really understand this issue, `xcode-select -p` can never return `/Applications/Xcode.app/Contents` unless one manually sets `DEVELOPER_DIR`:

```
$ sudo xcode-select -s /Applications/Xcode.app/
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
$ sudo xcode-select -s /Applications/Xcode.app/Contents/
xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/'
$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer/
$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/Library/
xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/Developer/Library/'
```

**Comment by kylef** [comment]
Hmm, you're right. My 4am bug debugging was fundamentally flawed.

I ran the `nm` command on fish shell so that failed (you can see output above) then I looked at source and didn't spot the `.dirname` call removing the `Developer` dir. So I assumed that `/Applications/Xcode.app/Contents/Developer/` was used and therefore would have the incorrect path.
