### ISSUE TITLE
How to use it to add files to xcodeproj

### ISSUE THREAD

**Issue by Draveness** [CocoaPods/Xcodeproj#266]
I google this but didn't find any pieces of code can run. And I find nothing in this document about this...And what is the `source_tree` is it a group?

**Comment by orta** [comment]
Here's an example of finding/creating a group, then adding a file to it: https://github.com/CocoaPods/cocoapods-acknowledgements/blob/master/lib/cocoapods_acknowledgements.rb#L8-L26

**Comment by Draveness** [comment]
Thx a lot!

**Comment by Draveness** [comment]
Why do I add files with this code, the compiler remind me file not exist? Is the file path relative to the root folder?

```
    j = JSON.parse File.read(json_path)
    project = Xcodeproj::Project.open(path)
    
    group_path = 'DKNightVersion/Pod/Classes/UIKit/'
    j.each do |group, files|
        new_group = project.main_group.find_subpath(File.join(group_path, group), true)
        files.each do |f|
            puts f
            new_group.new_file(f)
        end
    end
    project.save
```
![e655999b-013a-40b8-b14f-43df3699790a](https://cloud.githubusercontent.com/assets/6493255/7486790/21f0ed34-f3dd-11e4-9826-cc6cce9ce00a.png)
![323f5e01-a54d-484f-9831-d7a966c39bd6](https://cloud.githubusercontent.com/assets/6493255/7486791/2438e6e6-f3dd-11e4-8d4d-1d72273a0638.png)

**Comment by Draveness** [comment]
I find these file are not in compile sources how can I add these files to it..

**Comment by orta** [comment]
you also have to add it to the build phases alas

**Comment by Draveness** [comment]
I have already fix it. Because I didn't set the source tree to SOURCE_ROOT

**Comment by asad-ali-10p** [comment]
solved?
