### ISSUE TITLE
Investigate native ruby ASCII project serialization

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/Xcodeproj#284]

**Comment by neonichu** [comment]
If this is about Linux support, I'd rather see us supporting the use of CF-Lite in some way than actually re-implementing this, as it is a constantly moving target to 1:1 match the output of Xcode.

**Comment by alloy** [comment]
I agree, regardless of Linux support or not, I believe your time is best spent on other things.

**Comment by segiddins** [comment]
Eh it doesn't seem to be that difficult, though? And notice I said serialization. I agree parsing would be insane, but to actually serialize (even with the comments) shouldn't be that hard?

**Comment by neonichu** [comment]
Being hard != being time consuming :)

**Comment by segiddins** [comment]
This is done. See https://github.com/CocoaPods/Nanaimo.
