### ISSUE TITLE
Build targets in post install hook

### ISSUE THREAD

**Issue by liamogierussell** [CocoaPods/Xcodeproj#289]
Hi,

Not sure if this is an issue or possible a missing feature or just something I haven't been able to find. But in my podfile I have a post install hook to add build phases to each of my pods targets (the build phase is used to generate a file i need when the project is opened). Is there a way to build targets in the pods project in the post-install stage? 

I am currently using 

```
system "xcodebuild -target #{target.name} -sdk iphonesimulator -configuration Debug build"
```

This works the second time I run pod install as this is building the current pods project in the directory as opposed to the pods project being generated which I am accessing in the post install hook. So what I need is something similar to 

```
post_install do |installer|
  installer.project.targets.each do |target|
          target.build()
   end 
end
```

Is there any way of doing this with Xcodeproj?

Thanks,
Liam.

**Comment by segiddins** [comment]
No, Xcodeproj only allows you to manipulate project files -- it doesn't act as an interface to Xcodebuild at all.

**Comment by liamogierussell** [comment]
Ok cool, thanks for the speedy response.
