### ISSUE TITLE
Linked Frameworks and Libinary

### ISSUE THREAD

**Issue by mengxiangyue** [CocoaPods/Xcodeproj#290]
I want to add a framework to project, how to do it? i am new to ruby and xcodeproj, thanks. And i am not good at English.

**Comment by mrackwitz** [comment]
Sorry, your question is not very clear. Do you want to [add a framework target to your project](http://www.rubydoc.info/gems/xcodeproj/Xcodeproj%2FProject%2FProjectHelper.new_target) or do you want an existing framework to the framework build phase of another target? Then it depends on whether you want to add a system framework or a third party framework. You will find some pointers how to achieve that in the [codebase of the CocoaPods gem](https://github.com/CocoaPods/CocoaPods).
Generally that's not the right place for such questions. Please ask for support rather on StackOverflow.

**Comment by onmyway133** [comment]
@mrackwitz I think he wants to add an existing framework
