### ISSUE TITLE
dyld warning on El Capitan

### ISSUE THREAD

**Issue by jlj** [CocoaPods/Xcodeproj#302]
Since I installed OS X El Capitan today, I get the dyld warnings below when running ruby scripts that use Xcodeproj. These scripts are run as NSTask from an OS X application.

````
2015-09-13 12:08:12.456 CodeFlow[2893:102854] Ruby script XcodeProjectConfig.rb error:
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path

2015-09-13 12:08:12.491 CodeFlow[2893:102856] Ruby script XcodeProjectConfig.rb error:
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path

2015-09-13 12:16:10.288 CodeFlow[2893:148499] Ruby script XcodeProjectConfig.rb error:
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
````

Apart from the warnings, the parsing and updates of the Xcode project seem to work just fine.

Context:
- xcodeproj-0.27.2
- OS X El Capitan 10.11 GM (15A282b)
- Xcode 7.0 GM (7A218)

*Note that this is probably the same issue as https://github.com/CocoaPods/CocoaPods/issues/4121 and I enter it as a new issue here only because I get it in a Xcodeproj-specific context. :)*

**Comment by phuonglm86** [comment]
Same here, just don't know why? 
Have you tried the pre version?

**Comment by AliSoftware** [comment]
@phuonglm86 see https://github.com/CocoaPods/CocoaPods/issues/4121#issuecomment-140103610

You can safely ignore them until we fix Xcodeproj to silence them (or until Apple fixes it)

**Comment by phuonglm86** [comment]
@AliSoftware, it seems the warning doesn't affect the usage of Cocoapods at all. Thank you for your response.

**Comment by segiddins** [comment]
Fixed by https://github.com/CocoaPods/Xcodeproj/pull/312.
