### ISSUE TITLE
Create new single view application for iOS

### ISSUE THREAD

**Issue by priteshshah1983** [CocoaPods/Xcodeproj#304]
Hi,
Is it possible to create a new single view application for iOS?

Thanks.

**Comment by AliSoftware** [comment]
Yes it is.

For questions about usage though, please use StackOverflow.
This place is only to report and track bugs in the project

**Comment by priteshshah1983** [comment]
Apologies. I created a SO question here: http://stackoverflow.com/questions/32772635/create-new-single-view-application-for-ios-using-command-line-tools
