### ISSUE TITLE
Illegal character in Projekt name

### ISSUE THREAD

**Issue by clausweymann** [CocoaPods/Xcodeproj#342]
If you name your project something like ProjectNames&Bugs pod install will fail because the workspace-xml (contents.xcworkspacedata) will not be valid.
results in `Illegal character '&' in raw string "group:ProjectNames&Bugs.xcodeproj"`

Should be fixed by changing file_reference_xml
`location = "#{file_reference.type.encode(:xml => :attr)}:#{file_reference.path.encode(:xml => :attr)}">`

right?

can't check myself at the moment because i can't install cocoapods from source because my ruby version (2.2.3) doesn't work with json 1.7.7 ...

**Comment by segiddins** [comment]
@clausweymann a PR with tests making this change would be ace :)

**Comment by chipp** [comment]
This issues was fixed in e6ab7cfc24c27363e9aa754254a67704e2ec27fd and also tested in workspace_spec b0443061a2c4ad85da672f1d6967976f0b86c485.
