### ISSUE TITLE
Generate plist file

### ISSUE THREAD

**Issue by mchiesa** [CocoaPods/Xcodeproj#352]
I'm trying to use the Xcodeproj gem to create an Xcode project from command line. Does xcodeproj generates a plist file also or should I generate the file myself (with the same content as Xcode does)?

Thanks

**Comment by orta** [comment]
It depends on what plist you're after, Xcodeproj can generate a the .xcodeproj if you call save on it. All of the Xcode Project templates aren't inside Xcodeproj the gem.

**Comment by alloy** [comment]
If you mean a `Info.plist` file, then you will have to generate one yourself. You can do so with the plist module in this gem, though: https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/plist.rb

**Comment by mchiesa** [comment]
Sorry that I didn't explain myself well. Yes I mean a Info.plist file.

I'm creating a command line tool that allows me to generate an Xcode project with a specific project structure and configuration. The script is already creating the project with a target and a couple files but I don't have the Info.plist yet. I'll take a look to the module you mentioned and try to generate it.

Thanks @orta and @alloy

**Comment by orta** [comment]
@mchiesa I'd recommend reading the the [code for Xcake](https://github.com/jcampbell05/xcake) (and it may do what you want anyway )
