### ISSUE TITLE
the 'xcodeproj' argument doesn't respect SWIFT_OPTIMIZATION_LEVEL flags

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/Xcodeproj#354]
exact copy of this issue: https://github.com/CocoaPods/CocoaPods/issues/4867

I'm having trouble using the "xcodeproj" (soon to be "project") argument in my Podfile.

I'm using the "xcodeproj" argument to describe which configurations should be treated as "debug" and which should be treated as "release" like this:

`xcodeproj 'SpecialProj', 'DEV' => :debug, 'QA' => :debug, 'PROD' => :release
`

While this flag does set the optimization levels correctly for Apple LLVM 7.0, it does not do something similar for the Swift compiler. Shouldn't it?

**Comment by skydivedan** [comment]
I'm using cocopods 0.39, and Xcode 7.2

**Comment by segiddins** [comment]
In debug on master it seems to be set to `SWIFT_OPTIMIZATION_LEVEL = -Onone`, so...

**Comment by skydivedan** [comment]
Yes, the "debug" configuration does get set to "-0none", but the rest of the configs don't.

If I select the "Pods" project in my workspace, I see this:
<img width="469" alt="screen shot 2016-02-05 at 12 57 17 pm" src="https://cloud.githubusercontent.com/assets/217969/12854511/1acee75a-cc08-11e5-99e7-b316d8d99ea2.png">

notice how "DEV" and "QA" have their flags set, in the LLVM section, but NOTHING in the Swift Compiler section.

*however*, I select an individual pod from the target list, there is a "Debug" configuration, and it is set to -0none.  However, DEV & QA configs are not, and set to "Fast[-0]"

**Comment by segiddins** [comment]
If they're not set, they'll use the default. Same as when you create a new framework via the Xcode new target menu.

**Comment by skydivedan** [comment]
OK, here's a video of what I'm doing. 
https://youtu.be/6srQt_00dAU

It's 5 minutes long, unedited. I do the following:
1. Create a new Framework & Library, and then show the optimization settings in Release & Debug.
2. I create three new configs, named DEV, QA and PROD. (only PROD is based on Release).
3. I close the project, go into terminal and create a new Podfile, and specify the xcodeproj flag.
(there was a typo, which caused an error when doing 'pod update', so you see me fix it).
4. I do a 'pod update', and then open the workspace file.
5. I show the optimization settings for the main project, then the Pods project.

End result is while the config named "Debug" does have Swift optimizations turned to "none", QA & DEV do not (although the do in the LLVM).

**Comment by segiddins** [comment]
Issue stems from https://github.com/CocoaPods/Xcodeproj/blob/b31f101a2ac1d117403d5d472c620dd1e31469eb/lib/xcodeproj/project/project_helper.rb#L192, I could reproduce it -- basically, whether a build configuration is based on debug or release isn't persisted
