### ISSUE TITLE
Setting Info.plist file to a newly created target.

### ISSUE THREAD

**Issue by JakielaAdam** [CocoaPods/Xcodeproj#361]
I have successfully used xcodeproj to create a target. Once created I would like to set the Info.plist file for the new target. Is this possible with xcodeproj? After looking through the docs and searching Google I have not found any way to do this. 

Thanks for the great project!

**Comment by segiddins** [comment]
This question was asked at https://github.com/CocoaPods/Xcodeproj/issues/352 and there are a few good answers in there

**Comment by JakielaAdam** [comment]
Thanks for the reply. It seems like most of these answers regard creating a plist file. I am already generating a plist file. I want to assign a preexisting plist file to a newly created project. Sorry for not being clear on that.

**Comment by segiddins** [comment]
You can assign to the `INFO_PLIST_FILE` build setting, iirc.

**Comment by JakielaAdam** [comment]
I can see where I can retrieve the build setting for a target. Is there anyway with xcodeproj that I can add/modify a build setting attribute such as `INFO_PLIST_FILE`?

**Comment by segiddins** [comment]
`target.build_configurations.each {|bc| bc.settings['INFO_PLIST_FILE'] = 'FOO' }` should do it

**Comment by JakielaAdam** [comment]
The line within the loop should be ` bc.build_settings['INFOPLIST_FILE'] = 'FOO'` but thanks that did the trick.
