### ISSUE TITLE
Structure mismatch between XCScheme created by "Xcode" & "recreate_user_schemes" function

### ISSUE THREAD

**Issue by chintan1891** [CocoaPods/Xcodeproj#365]
I have tried creating user scheme of my project by "recreate_user_schemes".
I compared it with the scheme generated by xcode & found below difference.

![screen shot 2016-04-14 at 11 05 27 am](https://cloud.githubusercontent.com/assets/2618686/14517987/de12f586-0230-11e6-9e99-d57484160cd4.png)

Is there any way to generated same files as xcode is generating.

Also attaching both files:

1) Generated by Xcode
[TestCases_Xcode.xcscheme.txt](https://github.com/CocoaPods/Xcodeproj/files/218443/TestCases_Xcode.xcscheme.txt)

2) Generated by Xcodeproj function
[TestCases_XCodeproj.xcscheme.txt](https://github.com/CocoaPods/Xcodeproj/files/218444/TestCases_XCodeproj.xcscheme.txt)

**Comment by segiddins** [comment]
What version of Xcodeproj are you using? I'm also not really seeing a structure mismatch there

**Comment by chintan1891** [comment]
@segiddins  I am using version 0.28.2.

If you check screenshot, you will find that "Testable" & "MacroExpansion" nodes are not generated.

**Comment by segiddins** [comment]
Right, but why would they be generated by default? They've added by Xcode when you add a test target.

**Comment by chintan1891** [comment]
@segiddins  Currently i have a scenario where i have to recreate user schema with xcodeproj & i also need Testable & MacroExpansion node into that Scheme file.

**Comment by segiddins** [comment]
I think you'll need to explicitly add them back then

**Comment by chintan1891** [comment]
Ok, i will do that.. Thanks...
