### ISSUE TITLE
project_diff converts nil to yaml

### ISSUE THREAD

**Issue by bootstraponline** [CocoaPods/Xcodeproj#368]
[project_diff.rb](https://github.com/CocoaPods/Xcodeproj/blob/51f06149fc109d8e8127888c2835e7e6feec16c7/lib/xcodeproj/command/project_diff.rb#L48)
```ruby
yaml = diff.to_yaml
```

When diff is nil, the yaml output is:

```
> nil.to_yaml
=> "--- \n...\n"
```

I think empty string is the correct output on a nil diff.

**Comment by segiddins** [comment]
But then it won't be a full YAML document.... It's a tough call

**Comment by bootstraponline** [comment]
ok, maybe just leave it as is then. I can just detect `"--- \n...\n"` as nil in my wrapper code.

**Comment by segiddins** [comment]
👍
