### ISSUE TITLE
Use LastUpgradeCheck 0730

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/Xcodeproj#370]
Otherwise the user gets an "Update to recommended project settings warning" from XCode 7.3.

Downstream bug: https://github.com/CocoaPods/pod-template/issues/131

Also, follow other changes recommended by XCode 7.3.

**Comment by segiddins** [comment]
This will probably be addressed by someone going through and re-running the build settings rebuild rake task with Xcode 7.3 before the Xcodeproj 1.0 release
