### ISSUE TITLE
Unable to set code signing option in PBXCopyFilesBuildPhase

### ISSUE THREAD

**Issue by bzarzoza** [CocoaPods/Xcodeproj#373]
I can add a file ref to the copy files phase, no problem - but it appears that there is no (documented) way to set the 'Code Sign On Copy' checkbox that appears in xcode.

**Comment by bzarzoza** [comment]
Closing, figured it out.

**Comment by luowenxing** [comment]
build_file.settings = { 'ATTRIBUTES' => ['CodeSignOnCopy', 'RemoveHeadersOnCopy'] }

**Comment by luowenxing** [comment]
https://github.com/CocoaPods/Xcodeproj/issues/408
