### ISSUE TITLE
Add third party .framework files to an existing .xcodeproj

### ISSUE THREAD

**Issue by cosminstirbu** [CocoaPods/Xcodeproj#388]
Hi,

This is more of a documentation question.
I am trying to automate the addition of a third party .framework file to an existing .xcodeproj and also adding it in the Linked Frameworks and Libraries section.

How would you recommend doing that?
I did look at the documentation but I couldn't really figure it out http://www.rubydoc.info/gems/xcodeproj

Thank you,
Cosmin

**Comment by segiddins** [comment]
`target.frameworks_build_phases.add_file_reference` should do it!
