### ISSUE TITLE
Adding aggregate targets to a pod-template fails to install the template

### ISSUE THREAD

**Issue by pkrmf** [CocoaPods/Xcodeproj#402]
Seems that having a template project with an Aggregate Target makes CocoaPods to fail when trying to call the function `def remove_demo_project` in the ProjectManipulator.rb file. Basically the ProjectManiuplator file wants to remove the application example target and its unit tests so it has to iterate through all the Targets on the project and find them.

I am guessing cocoa pods is trying to parse the project.pbxproj file and assign the variable product_type to each one of the targets. Apple doesn't provide a product_type for Aggregate Targets:

`/* Begin PBXAggregateTarget section */
		74D136291D62890A0015C7B3 /* PROJECTExport */ = {
			isa = PBXAggregateTarget;
			buildConfigurationList = 74D1362A1D62890A0015C7B3 /* Build configuration list for PBXAggregateTarget "PROJECTExport" */;
			buildPhases = (
				74D1362D1D62890E0015C7B3 /* ShellScript */,
			);
			dependencies = (
			);
			name = "PROJECTExport";
			productName = "PROJECTExport";
		};
/* End PBXAggregateTarget section */`

Is there any workaround to include an Aggregate Target to Project Template? I tried adding it myself and assign a value to it, but obviously it fails `/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:321:in configure_with_plist: [!] Xcodeproj doesn't know about the following attributes {"productType"=>"com.apple.product-type.application"} for the 'PBXAggregateTarget' isa. (RuntimeError)`

Could CocoaPods prevent to assign the product_type variable to a Target that doesn't have a product_type variable?

**Comment by segiddins** [comment]
Can you please open up an issue in the CocoaPods repo including the full issue template CocoaPods prints when it encounters an unexpected error? Thanks!

**Comment by pkrmf** [comment]
U guys are awesome!
