### ISSUE TITLE
How to add an framework to Xcode.project Embedded Binaries section

### ISSUE THREAD

**Issue by draveness** [CocoaPods/Xcodeproj#408]

**Comment by SHiLLySiT** [comment]
I'm also curious about this - I've been digging through the documentation and it seems like it may not be currently possible?

**Comment by benasher44** [comment]
You can add to the Target Dependencies build phase. That's what I think of when I think "embedded"

**Comment by Draveness** [comment]
![0d20782f-e401-440f-9f9e-d97bfc62630b](https://cloud.githubusercontent.com/assets/6493255/18555617/1a9ae098-7b9b-11e6-96e3-fafeab7e314b.png)

it's not target dependencies =, =

**Comment by jpsim** [comment]
I came here looking for how to do this, ended up writing my own. It was pretty simple:

```ruby
# Replace these with your values
project_location = '/path/to/MyApp.xcodeproj'
target_name = 'MyApp'
framework_root = '/framework/parent/directory'
framework_name = 'MyFramework.framework'

# Get useful variables
project = Xcodeproj::Project.open(project_location)
frameworks_group = project.groups.find { |group| group.display_name == 'Frameworks' }
target = project.targets.find { |target| target.to_s == target_name }
frameworks_build_phase = target.build_phases.find { |build_phase| build_phase.to_s == 'FrameworksBuildPhase' }

# Add new "Embed Frameworks" build phase to target
embed_frameworks_build_phase = project.new(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
embed_frameworks_build_phase.name = 'Embed Frameworks'
embed_frameworks_build_phase.symbol_dst_subfolder_spec = :frameworks
target.build_phases << embed_frameworks_build_phase

# Add framework search path to target
['Debug', 'Release'].each do |config|
  paths = ['$(inherited)', framework_root]
  target.build_settings(config)['FRAMEWORK_SEARCH_PATHS'] = paths
end

# Add framework to target as "Embedded Frameworks"
framework_ref = frameworks_group.new_file("#{framework_root}/#{framework_name}")
build_file = embed_frameworks_build_phase.add_file_reference(framework_ref)
frameworks_build_phase.add_file_reference(framework_ref)
build_file.settings = { 'ATTRIBUTES' => ['CodeSignOnCopy', 'RemoveHeadersOnCopy'] }

# Save Xcode project
project.save
```

**Comment by swl367** [comment]
@jpsim Thanks for your snippet. I've gotten everything to be successful except one last part. The actual .framework item isn't be added under the Xcode "Linked Frameworks" section.

I'm supplying the absolute path to the script; it seems like the build phase "add_file_reference" is causing some issue.

Thanks :)

See attached image.
![screen shot 2016-11-28 at 6 20 38 pm](https://cloud.githubusercontent.com/assets/1043014/20691584/8e708726-b597-11e6-9429-bb977c1fa68e.png)

**Comment by jpsim** [comment]
If it's useful to anyone, this is where we use the script "in production": https://github.com/realm/RealmTasks/blob/v0.2.3/.packaging/package_release.rb

**Comment by revolter** [comment]
You can simply use:

```ruby
embed_frameworks_build_phase = target.new_copy_files_build_phase('Embed Frameworks')
```

instead of:

```ruby
embed_frameworks_build_phase = project.new(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
embed_frameworks_build_phase.name = 'Embed Frameworks'
target.build_phases << embed_frameworks_build_phase
```

**Comment by HenriqueMatias** [comment]
> I came here looking for how to do this, ended up writing my own. It was pretty simple:
> 
> ```ruby
> # Replace these with your values
> project_location = '/path/to/MyApp.xcodeproj'
> target_name = 'MyApp'
> framework_root = '/framework/parent/directory'
> framework_name = 'MyFramework.framework'
> 
> # Get useful variables
> project = Xcodeproj::Project.open(project_location)
> frameworks_group = project.groups.find { |group| group.display_name == 'Frameworks' }
> target = project.targets.find { |target| target.to_s == target_name }
> frameworks_build_phase = target.build_phases.find { |build_phase| build_phase.to_s == 'FrameworksBuildPhase' }
> 
> # Add new "Embed Frameworks" build phase to target
> embed_frameworks_build_phase = project.new(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
> embed_frameworks_build_phase.name = 'Embed Frameworks'
> embed_frameworks_build_phase.symbol_dst_subfolder_spec = :frameworks
> target.build_phases << embed_frameworks_build_phase
> 
> # Add framework search path to target
> ['Debug', 'Release'].each do |config|
>   paths = ['$(inherited)', framework_root]
>   target.build_settings(config)['FRAMEWORK_SEARCH_PATHS'] = paths
> end
> 
> # Add framework to target as "Embedded Frameworks"
> framework_ref = frameworks_group.new_file("#{framework_root}/#{framework_name}")
> build_file = embed_frameworks_build_phase.add_file_reference(framework_ref)
> frameworks_build_phase.add_file_reference(framework_ref)
> build_file.settings = { 'ATTRIBUTES' => ['CodeSignOnCopy', 'RemoveHeadersOnCopy'] }
> 
> # Save Xcode project
> project.save
> ```

Do you know how can I do this for the "Linked frameworks and libraries" section?

**Comment by dantoml** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests.

**Comment by serp1412** [comment]
For anybody that's still looking, it looks like `PBXNativeTarget` has a method `frameworks_build_phase` which will return the Embed Frameworks phase. So you don't have to create it. At least it worked for my app. 

The rest of the answer is still valid
