### ISSUE TITLE
Lost ability to mutate Xcodeproj::Workspace.file_references

### ISSUE THREAD

**Issue by jpsim** [CocoaPods/Xcodeproj#417]
Has this been made immutable in the last few versions? We used to have this code that removed references to `Realm.xcodeproj` in a workspace, and it no longer works:

```ruby
def remove_reference_to_realm_xcode_project(workspace_path)
  old_workspace = Xcodeproj::Workspace.new_from_xcworkspace(workspace_path)
  old_workspace.file_references.reject! do |file_reference|
    file_reference.path == "../../../Realm.xcodeproj"
  end

  File.open("#{workspace_path}/contents.xcworkspacedata", "w") do |file|
    file.puts old_workspace
  end
end
```

**Comment by jpsim** [comment]
Any word on this?

**Comment by benasher44** [comment]
@jpsim according to `git blame`, `file_references` on the `Xcodeproj::Workspace` object has looked like:
```
    def file_references
      return [] unless @document
      @document.get_elements('/Workspace//FileRef').map do |node|
        FileReference.from_node(node)
      end
    end
```
since ~ Oct, 2015. I'm not sure how the code you posted could work, since it looks like `file_references` builds a new array each time.

**Comment by jpsim** [comment]
ok, thanks @benasher44
