### ISSUE TITLE
Update Last Known OS Constants to latest iOS, macOS, etc. 

### ISSUE THREAD

**Issue by rcgilbert** [CocoaPods/Xcodeproj#422]
The `LAST_KNOWN_...` constants need to be updated in [constants.rb](https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb).  This is currently breaking adding system frameworks in Xcode 8.

**Comment by louisdh** [comment]
Fixed in #468?

**Comment by benasher44** [comment]
Yep! Thanks! Closing.
