### ISSUE TITLE
Support for interpolating build setting vars?

### ISSUE THREAD

**Issue by mikelambert** [CocoaPods/Xcodeproj#423]
When I run `xcodeproj show`, I see:
```
    Build Configurations:
    - Debug:
        Build Settings:
          BUNDLE_ID_SUFFIX: ".debug"
          PRODUCT_BUNDLE_IDENTIFIER: com.DanceDeets.ios$(BUNDLE_ID_SUFFIX)
          PRODUCT_NAME: DanceDeets Debug
```

Is there a way to output the final `PRODUCT_BUNDLE_IDENTIFIER: com.DanceDeets.ios.debug` from `xcodeproj` command, which is what I really care about for the Debug build configuration?

For background, I just discovered `xcodeproj` command today, and seems to be the key to fixing the React Native JS-based build scripts. I have a debug and release config with different product names and bundle identifiers, which React Native build scripts don't support natively, and instead make incorrect assumptions at a few points in the build process.

**Comment by segiddins** [comment]
I think that might be out of scope for Xcodeproj? On the other hand, `xcodebuild -showBuildSettings` might already be able to do this

**Comment by mikelambert** [comment]
Oh wow, thank you! Sorry for the false alarm in barking up the wrong tree with my searching, that command does exactly what I'm looking for.

**Comment by segiddins** [comment]
No worries!
