### ISSUE TITLE
Cannot change directory after project save

### ISSUE THREAD

**Issue by liamogierussell1** [CocoaPods/Xcodeproj#426]
Hi,

I have been reading about the breaking changes since XCode 8 beta 4 and how it prevents subsequent calls to chdir. I have created the simplest example I could to show reproduce this issue.

`require 'xcodeproj'

puts Dir.pwd
Dir.chdir "fastlane"
puts Dir.pwd
Dir.chdir "../"
puts Dir.pwd
# Open the XCode project

project = Xcodeproj::Project.open("MyProject.xcodeproj")
# Save project changes

project.save()

puts Dir.pwd
Dir.chdir "fastlane"
puts Dir.pwd
Dir.chdir "../"
puts Dir.pwd`

This produces the output 

/Users/username/projectname-ios-swift-3
/Users/username/projectname-ios-swift-3/fastlane
/Users/username/projectname-ios-swift-3
/Users/username/projectname-ios-swift-3
/Users/username/projectname-ios-swift-3
/Users/username/projectname-ios-swift-3

So prior to calling save i am able to successfully change to the fastlane directory and back, however afterwards it stays in the same directory. I have tried using the suggested __pthread_chdir but i get an error "undefined method `__pthread_chdir' for Dir:Class" when using Dir.__pthread_chdir "fastlane".  Same error when trying to use actually_chdir shown here http://www.rubydoc.info/gems/xcodeproj/1.3.1/Xcodeproj/Plist/Extensions/Dir#actually_chdir and I am on xcodeproj (1.3.1).

Is there a workaround for this to allow me to change directory after saving the project or a release I am unaware of that fixes this? I am on the 1.1.0.rc.2 cocoapods release.

Thanks,
Liam.

**Comment by orta** [comment]
Yeah, we keep finding new ways that this breaks things - our last attempt isn't shipped yet https://github.com/CocoaPods/Xcodeproj/pull/421 

You can give master a try with a Gemfile to see if that fixes it?

**Comment by liamogierussell1** [comment]
Hey, thanks for the quick response. Master doesn't seem to fix the issue around saving, the example above had the same output. But that was with no changes to the script above, i assumed i should be calling actually_chdir but that was still undefined.

I am using XCodeProj as part of fastlane and the issue manifested with fastlane not changing directories correctly after saving the project when pointed at XCode 8.

However I was able to take the method in the PR and add that to my fastfile to allow me to replicate the directory changes fastlane makes to get around the issue for now.

**Comment by DanToml** [comment]
@liamogierussell1 huh, interesting, I'll try to do some digging around later. Another potential short term workaround is setting the `FORK_XCODE_WRITING` env var to true.

**Comment by liamogierussell1** [comment]
Thanks for the suggestion @DanToml, that fixed the problem too.

Just to provide a bit more information to explain the workflow for this if it helps debug.

My fastfile calls a custom fastlane action which modifies the project with XCodeProj. I have logged out the working directory before the action and after the action returns to my fastfile. If i remove the call to project.save() in my action i get the following output from Dir.pwd

/Users/username/project-ios-swift-3/fastlane
/Users/username/project-ios-swift-3/fastlane

So before it goes into the action the current directory is the fastlane directory and is also the fastlane directory again when it returns to the fastfile.

If I add back in the line project.save(), the output before the action and after is
/Users/username/project-ios-swift-3/fastlane
/Users/username/project-ios-swift-3

So it has moved to the root of the project when it returns to the fastfile.

And finally with ENV["FORK_XCODE_WRITING"] = 'true' it correctly returns to
/Users/username/project-ios-swift-3/fastlane
/Users/username/project-ios-swift-3/fastlane

Let me know if there's anymore information that can help.

**Comment by Eldorado234** [comment]
Had the same issue, for me it's fixed on `master`.

**Comment by humblehacker** [comment]
As noted in https://github.com/fastlane/fastlane/issues/6499, I'm having the same issue.  Using `xcodeproj` from `master` didn't help, but the suggestion of @liamogierussell1, to use `FORK_XCODE_WRITING` did work.  To be clear, I executed fastlane like this:

**Comment by Eldorado234** [comment]
Fixed for me using `1.4.1`.

**Comment by DanToml** [comment]
This is fixed by upgrading to 1.4.0 or greater which started to use https://github.com/CocoaPods/Nanaimo instead of using Xcode frameworks.
