### ISSUE TITLE
Delete a key and the relative value

### ISSUE THREAD

**Issue by taglia3** [CocoaPods/Xcodeproj#434]
Hi,

how I can delete the key and the relative value from the project file?

actually I have this code:

```
project = Xcodeproj::Project.open(PROJECT_PATH)

project.targets.each do |target|
  puts target.name
 target.build_configurations.each do |config|
    config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Distribution'
  end
end

project.save
```

But I want also delete the key _CODE_SIGN_IDENTITY[sdk=iphoneos*]_ and the relative value.
Exists something like this?

`config.build_settings.delete(key_to_delete)`

Thanks

**Comment by segiddins** [comment]
That exact code snippet should work, since ruby hashes have a `delete` method

**Comment by taglia3** [comment]
Hi segiddins,

yes that's right!
Firstly it doesn't works because I was using the no escaping characters for the key name:

`config.build_settings.delete('CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]')`

With the fix it works perfectly:

`config.build_settings.delete('CODE_SIGN_IDENTITY[sdk=iphoneos*]')`


Thanks!
