### ISSUE TITLE
How to create UnitTest/UITest Target

### ISSUE THREAD

**Issue by ZeroFengLee** [CocoaPods/Xcodeproj#436]
from Api, i found this:

#new_target(type, name, platform, deployment_target = nil, product_group = nil, language = nil) ⇒ PBXNativeTarget

type (Symbol) — the type of target. Can be `:application`, `:framework`, `:dynamic_library` or `:static_library`.

but there's no unitTest or UITest type. has any other way to create unitTest Target?

**Comment by segiddins** [comment]
See `Constants:: PRODUCT_TYPE_UTI`

**Comment by ZeroFengLee** [comment]
thanks
