### ISSUE TITLE
build_settings not work 

### ISSUE THREAD

**Issue by njafei** [CocoaPods/Xcodeproj#437]
XCode8 Xcodeproj1.3.1
when i use 
`project.targets.each do |target|
  puts target.name
end`

it works ,but when i try to change buildsetting ,it dose not work...

`project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['MY_CUSTOM_FLAG'] ||= 'TRUE'
  end
end`

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the Xcodeproj issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by njafei** [comment]
ok, get it.
