### ISSUE TITLE
crash some time

### ISSUE THREAD

**Issue by njafei** [CocoaPods/Xcodeproj#441]
sometimes ,it will crash 

logs: 

/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:271:in `ptr': uninitialized constant CoreFoundation (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:73:in `RubyHashPropertyListRead'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi.rb:87:in `read_from_path'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist.rb:22:in `read_from_path'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:102:in `open'
	from /Users/server/.jenkins/jobs/tuniu_inhouse/workspace/tuniuapp-iphone/Iphone/python/codeSign/inhouseCodeSign.rb:2:in `<main>'

**Comment by segiddins** [comment]
This should be fixed in Xcodeproj 1.4.0

**Comment by njafei** [comment]
yes,it works perfect in 1.4.1
