### ISSUE TITLE
How to create a new empty xcworkspace

### ISSUE THREAD

**Issue by AndrewSB** [CocoaPods/Xcodeproj#451]
Hey!

I was wondering if I could use this tool to generate a new `xcworkspace`, very similar to `Project.new`, where one simply passes in the path for which the project is to be created at?

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) where people can help out with questions like this. We try to keep the Xcodeproj issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by AndrewSB** [comment]
Sorry about the noise @segiddins!

I'll ask on SO 😄
