### ISSUE TITLE
nil build setting value causes corrupted pbxproj file

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/Xcodeproj#453]
I had these lines in my project's `Podfile`:

```ruby
post_install do |installer|
	installer.pods_project.build_configuration_list.build_settings('Release')['SWIFT_OPTIMIZATION_LEVEL'] = ENV['SWIFT_OPTIMIZATION_LEVEL']
end
```

When the `SWIFT_OPTIMIZATION_LEVEL` environment variable is not set, the created pbxproj file contains this line:

```
SWIFT_OPTIMIZATION_LEVEL = ;
```

This prevents Xcode from successfully parsing the file.

It used to work several weeks ago, but I cannot tell what's changed. Maybe environment variables which were not set did return an empty string in earlier Ruby versions, maybe xcodeproj was handling such cases better.

Instead of creating a corrupted pbxproj file, xcodeproj should either
- convert the build setting value to a string first, e.g. `SWIFT_OPTIMIZATION_LEVEL = "";` or
- throw an error stating that a nil value is not allowed.

**Comment by segiddins** [comment]
Thanks, https://github.com/CocoaPods/Nanaimo/issues/19 should fix this!
