### ISSUE TITLE
configuration_list.rb:101:in `ascii_plist_annotation': undefined method `isa' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by nbalakirevs** [CocoaPods/Xcodeproj#470]
xcodeproj won't build the newly created project based on Cocoa Touch Static Library (iOS) template.
 
```
.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object/configuration_list.rb:101:in `ascii_plist_annotation': undefined method `isa' for nil:NilClass (NoMethodError)
Did you mean?  is_a?
	from /Users/NikitaB/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:301:in `block in to_ascii_plist'
	from /Users/NikitaB/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:291:in `each'
	from /Users/NikitaB/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:291:in `to_ascii_plist'
	from /Users/NikitaB/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:372:in `block in save'
	from /Users/NikitaB/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:372:in `open'
	from /Users/NikitaB/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:372:in `save'
	from ./update_project:9:in `<main>'
```

So I just create a sample project based on Cocoa Touch Static Library (iOS) template.  After that I created a simple scrip that will create xcodeproj file based on already existing one.

```
#!/usr/bin/env ruby

require 'xcodeproj'

project_file = 'StaticLibraryDefaultProject.xcodeproj'
project = Xcodeproj::Project.new(project_file)
project.initialize_from_file

project.save

```

Unfortunately calling `save` in the script causes an error which I posted above.

Please find below the project that I create.
[StaticLibraryDefaultProject.zip](https://github.com/CocoaPods/Xcodeproj/files/824782/StaticLibraryDefaultProject.zip)

**Comment by segiddins** [comment]
Try using `Xcodeproj::Project.open` instead of `new` and `initialize_from_file` ?

**Comment by nbalakirevs** [comment]
Using `Xcodeproj::Project.open` solves the issue. But I need to have a new project based on existing one. Then I generate *.m and *.h files which I later add to the project. If I would use Xcodeproj::Project.open then files that were added and generated last time would be added again and I will end up with duplicates in XCode project.

**Comment by Desnoo** [comment]
Well why not filter out the duplicates. Fetch the filereferences of the duplicates and remove them by calling `remove_file_reference(file_ref) ` for each of them.  Have a look at the [code documentation](http://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project).

**Comment by nbalakirevs** [comment]
@Desnoo @segiddins Good idea. Thanks for the tip. I will use open command instead of a new and just remove the existing references.
