### ISSUE TITLE
Danger is failing because of a broken dangerfile

### ISSUE THREAD

**Issue by DanToml** [CocoaPods/Xcodeproj#493]
Looks like something related to prs has changed since we wrote the dangerfile. Filing this mostly so I don't forget to fix it later.
https://travis-ci.org/CocoaPods/Xcodeproj/jobs/238766019

**Comment by segiddins** [comment]
Given we haven't changed anything on here or on CocoaPods/CocoaPods relating to danger in months, why would it have stopped working all of a sudden?

**Comment by DanToml** [comment]
@segiddins maybe it was always partially broken on this repo? otherwise I have no idea

**Comment by orta** [comment]
I saw some weird behaviour with the github API yesterday, lets see if this is an odd edge case

**Comment by segiddins** [comment]
Ping on this, it's blocking merging anything

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/Xcodeproj/pull/498
