### ISSUE TITLE
Support to remove localizations?

### ISSUE THREAD

**Issue by TheDom** [CocoaPods/Xcodeproj#494]
Is it possible to remove certain localizations with this gem? I would like to automate https://stackoverflow.com/a/27259678.

I searched through the docs but could not find support. I am also aware of https://github.com/CocoaPods/Xcodeproj/issues/85 but this seems like a different issue.

**Comment by TheDom** [comment]
I was able to figure it out with a lot of help from @AliSoftware. Thank you! :)

```
project = Xcodeproj::Project.open("Project.xcodeproj")

project.files.select { |f| f.path.start_with?('de.lproj/') }.each do |file|
  file.remove_from_project()
end

project.root_object.known_regions.delete('de')
project.save
```

**Comment by AliSoftware** [comment]
@TheDom improved and cleaner solution, which checks if the file ref is a `PBXVariantGroup` of name `de` before removing it instead of relying on the `path`

```ruby
require 'xcodeproj'

def remove_localization(project_path, lang)
  p = Xcodeproj::Project.open(project_path)
  project.files.select do |file|
    file.parent.is_a?(Xcodeproj::Project::Object::PBXVariantGroup) && file.name == lang
  end.each(&:remove_from_project)
  p.root_object.known_regions.delete(lang)
  p.save
end

remove_localization('YourProject.xcodeproj', 'de')
```
