### ISSUE TITLE
How to add custom static library file .a to Link Binary With Libraries

### ISSUE THREAD

**Issue by luowenxing** [CocoaPods/Xcodeproj#503]
I need to add a binary library with '.a' extension to `Link Binary With Libraries` in `Build Phase` as below
<img width="418" alt="screen shot 2017-08-21 at 8 37 47 pm" src="https://user-images.githubusercontent.com/7497114/29519617-a89c5b08-86b0-11e7-839c-7869ff5d86be.png">
I tried to use `target.add_file_references` but it doesn't work.It just add my .a file to `Compile Sources` instead of `Link Binary With Libraries`.
The custom framework file can be added to it using `target.frameworks_build_phases.add_file_reference`.What for custom binary *.a file?

**Comment by Kmohamed** [comment]
@luowenxing did you manage to make it ?

**Comment by Kmohamed** [comment]
@luowenxing you can make it using this command 
['Debug', 'Release'].each do |config|
  target.build_settings(config)[' OTHER_LDFLAGS'] = framework_path
end

**Comment by ArtemovRM** [comment]
@luowenxing 
`build_phase = target.frameworks_build_phase
  framework_group = project.frameworks_group
  file_ref = framework_group.new_reference('lib.a')
  file_ref.source_tree = 'SDKROOT'
  build_file = build_phase.add_file_reference(file_ref)`
Next, in build_setting OTHER_LDFLAGS = $(inherited) "path/to/lib.a"

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by HimiGame** [comment]
> @luowenxing
> 
> ```
> build_phase = target.frameworks_build_phase
> framework_group = project.frameworks_group
> file_ref = framework_group.new_reference('lib.a')
> file_ref.source_tree = 'SDKROOT'
> build_file = build_phase.add_file_reference(file_ref)
> ```
> 
> Next, in build_setting `OTHER_LDFLAGS = $(inherited) "path/to/lib.a"`

yep, podspec -> like this:
s.xcconfig = {'OTHER_LDFLAGS' => '$(PROJECT_DIR)/../../xxx/xxx.a'}
