### ISSUE TITLE
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")

### ISSUE THREAD

**Issue by danyating** [CocoaPods/Xcodeproj#522]
when I try `infer -- xcodebuild clean build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos`, I get error like "Nothing to compile. Try running xcodebuild clean build scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos clean first."

Then I try `infer --keep-going --no-xcpretty -- xcodebuild clean build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos`,The error above is gone, but I get a new error like
"
**BUILD FAILED**
Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")
"

However, the build command ` xcodebuild clean build -scheme appName -workspace appName.xcworkspace -configuration Debug -sdk iphoneos` can run sucessfully.

Is there something I can do to solve this problem?

**Comment by dnkoutso** [comment]
Does not appear a cocoapods library issue. Please attach a sample project demonstrating issue with cocoapods library itself.
