### ISSUE TITLE
How to add File to Xcode project using command line tool (Terminal)

### ISSUE THREAD

**Issue by sandeee1928** [CocoaPods/Xcodeproj#526]
Hi,
I didn't find any documentation to using this tool to add file to Xcode project using terminal.
In the help (xcodeproj --help) I and only see five options (config-dump, project-diff, show, sort and target-diff).

**Comment by dnkoutso** [comment]
This kind of question is best asked in StackOverflow. look for `add_file` or `add_file_reference` in the sources.
