### ISSUE TITLE
CLANG_ENABLE_OBJC_WEAK = YES fails all the builds for apps using __weak

### ISSUE THREAD

**Issue by vorobievalex** [CocoaPods/Xcodeproj#544]
Version 1.5.5 fails builds with:
clang: error: -fobjc-weak is not supported on the current deployment target

CLANG_ENABLE_OBJC_WEAK = YES added -fobjc-weak compilation option, what was disabled in project settings.

Regression of https://github.com/CocoaPods/Xcodeproj/commit/f356891db634b68710b5c78611b84c14371acd7a

**Comment by segiddins** [comment]
Xcode 9.3 defaults `CLANG_ENABLE_OBJC_WEAK` to `YES`

**Comment by segiddins** [comment]
what deployment does your target have?

**Comment by segiddins** [comment]
Looks like the mapping for deployment targets is:

```cpp
case FragileMacOSX: return getVersion() >= VersionTuple(10, 7);
case MacOSX: return getVersion() >= VersionTuple(10, 7);
case iOS: return getVersion() >= VersionTuple(5);
case WatchOS: return true;
```

**Comment by segiddins** [comment]
Can you see if https://github.com/CocoaPods/Xcodeproj/pull/546 fixes things for you? Thanks!

**Comment by nivanchikov** [comment]
@segiddins I'm also facing this issue on deployment target = 9.0. I didn't try lower or higher target versions. Maybe the issue is more related if MRC or ARC is used in specific pod library as opposed to making it a global setting?

**Comment by vorobievalex** [comment]
> Xcode 9.3 defaults CLANG_ENABLE_OBJC_WEAK to YES

The error appeared in some pods, that might not have this explicitly set, I guess.
Explicitly setting this to NO in the app project does not help.

> what deployment target does your target have?

This affected several apps with deployment target 8.2, 9.0 and 10.3.

**Comment by segiddins** [comment]
Can you share a project I can use to reproduce the issue (if indeed #546 does not fix it)?

**Comment by vorobievalex** [comment]
@segiddins, https://github.com/CocoaPods/Xcodeproj/pull/546 fixed this issue. Build succeed with this fix. Could it be released, please?
I just wanted to clarify earlier questions with my latest message above. Pardon for a miscommunication.

**Comment by segiddins** [comment]
Released

**Comment by vorobievalex** [comment]
@segiddins, thank you for a quick fix! Out team was able to quickly get back to the latest version of xcodeproj. Everything goes smoothly so far 👍

**Comment by HandongKim** [comment]
I had the same problem. But, finally, I solved the problem. The version of xcodeproj was searched for 1.5.5 and upgraded to 1.5.6, which solved the problem.

 sudo gem install xcodeproj
