### ISSUE TITLE
Issue when running in Travis

### ISSUE THREAD

**Issue by tcamin** [CocoaPods/Xcodeproj#545]
Just updated to 1.5.5 and now I'm getting the following error when running a Travis job

```/Users/travis/.rvm/gems/ruby-2.4.1/gems/atomos-0.1.1/lib/atomos.rb:8:in `atomic_write': undefined method `tmpdir' for Dir:Class (NoMethodError)
	from /Users/travis/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.5/lib/xcodeproj/project.rb:354:in `save'
	from MyProject/MyTarget/target_remover_for_travis.rb:25:in `<main>'```

**Comment by segiddins** [comment]
Thanks, I'll look into this

**Comment by segiddins** [comment]
https://github.com/segiddins/atomos/pull/2 should fix this, sorry!

**Comment by tcamin** [comment]
Great, thanks for the quick reply!

**Comment by segiddins** [comment]
Atomos v0.1.2 should fix this
