### ISSUE TITLE
1.5.5 broke `project.save` on Windows

### ISSUE THREAD

**Issue by janpio** [CocoaPods/Xcodeproj#549]
I work on making [fastlane](https://github.com/fastlane/fastlane) work on Windows, currently just by making the test suite pass. Back in December everything was good, but today I noticed several tests failing (see https://ci.appveyor.com/project/KrauseFx/fastlane/build/99) with this error message:

```
     Errno::EACCES:
       Permission denied @ rb_file_s_rename - (C:/Users/Jan/AppData/Local/Temp/.atomos.project.pbxproj20180214-11924-19mwsnc, C:/Projects/Fastlane/win-fastlane/fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj)
     # ./fastlane/lib/fastlane/actions/automatic_code_signing.rb:60:in `run'
```

Line 60 is just `project.save` (whith `project = Xcodeproj::Project.open(params[:path])` earlier. I still had the console open where I executed `bundle install` and noticed, that `xcodeproj` was updated from 1.5.4 to 1.5.6.

Downgrading to 1.5.4 again made the error go away, but as soon I return to 1.5.5 I get that error again - so I would say 1.5.5 somehow broke on Windows.

I looked through the commits, and the only commit that (I could find that) has to do with writing the file is https://github.com/CocoaPods/Xcodeproj/commit/df17a6db69494a65e17c4c1ba1ab2f1098f15a47 from @segiddins. Could this be a regression of that change?

(Update: Just noticed that the error message actually includes `.atomos` so I am pretty sure it has something to do with that change. Seems that instead of just writing over the file naively, this now creates the file in a tmp dir first and then tries to copy it back - which fails on Windows because... no idea. Probably some process is still locking the file.)

(Update 2: Which could also mean this is actually a bug or problem in `atomos` - but as @segiddins authored both the library and this change here, I will leave it with this issue instead of creating an additional one over at https://github.com/segiddins/atomos/issues if that is ok)

**Comment by segiddins** [comment]
Does `File.rename` not work on Windows? The docs don't mention anything about potential platform compatibility issues

**Comment by janpio** [comment]
No idea, sorry. I am not really a ruby programmer :/
Usually you get similar problems on Windows if another process is still accessing the file.

**Comment by janpio** [comment]
This is unfortunately still an issue with current version 1.5.9 which uses atomos (0.1.2)

As this is now a blocking issue for me for some things, I will create an issue for atomos and try to get this fixed somehow.

**Comment by janpio** [comment]
PR is merged, waiting for release of `atomos`.

**Comment by segiddins** [comment]
Released

**Comment by janpio** [comment]
Thanks! Should I send a PR that updates the `Gemfile.lock` and `xcodeproj.gemspec`? Not sure how this work with ruby/bundler.

**Comment by janpio** [comment]
Created that PR and it got merged, now waiting for new release.
