### ISSUE TITLE
Is there a way to apply a diff of an xcode project?

### ISSUE THREAD

**Issue by dylan-chong** [CocoaPods/Xcodeproj#555]

**Comment by amorde** [comment]
@dylan-chong  apologies for the very late response - yes, you can get a diff of two projects by using the `xcodeproj project-diff` command.

For details on that command, run `xcodeproj project-diff --help`

To get an idea of how to do this programmatically, here's the current implementation of that command:

https://github.com/CocoaPods/Xcodeproj/blob/0d6ed3aec8b325482954368c2b07d3645630ca29/lib/xcodeproj/command/project_diff.rb#L37-L53
