### ISSUE TITLE
workspace.schemes doesn't load schemes in the workspace container

### ISSUE THREAD

**Issue by loufranco** [CocoaPods/Xcodeproj#557]
Here is a simple Xcode workspace with 2 projects and a scheme that is in the Workspace (not one of the projects)

[WorkspaceSchemes.zip](https://github.com/CocoaPods/Xcodeproj/files/1831718/WorkspaceSchemes.zip)

I included an xc.rb to run

when you run it, it doesn't list WorkspaceSchemesScheme, which is here:

`./WorkspaceSchemes.xcworkspace/xcshareddata/xcschemes/WorkspaceSchemesScheme.xcscheme`

When you manage schemes you will see that this scheme is tied to the workspace, not a project.

`fastlane` has recently adopted xcodeproj and it uses `workspace.schemes` to get a list of schemes, which won't list this one.  It now can't build workspaces like this.

**Comment by loufranco** [comment]
I'd be happy to contribute a fix, but I would need some guidance on what you want.

If `Workspace.load_schemes` would load these, is it ok to map from the scheme name to the workspace filename.

Or, to maintain backwards compatibility (since that function says it loads project schemes), should you add `Workspace.load_workspace_schemes` to do that?

I'm ambivalent to the solution -- `fastlane` just uses the keys of this map, so whatever xcodeproj does is probably fine for them.

**Comment by DanToml** [comment]
@loufranco We should probably roll this into the `load_schemes` method imo

**Comment by loufranco** [comment]
Ok, will post a PR soon

**Comment by foux** [comment]
Still the exact same problem in 1.6.0
