### ISSUE TITLE
Strange behaviour when resolving target build setting against xcconfig and without

### ISSUE THREAD

**Issue by ianbytchek** [CocoaPods/Xcodeproj#569]
While working on SiarheiFedartsou/fastlane-plugin-versioning#24 I came across a case when doing:

```ruby
target.resolved_build_setting('INFOPLIST_FILE', true) // SRCROOT/…/Info_Release.plist
target.resolved_build_setting('INFOPLIST_FILE', false) // $(SRCROOT)/…/Info_Release.plist
```

Shouldn't it resolve $SRCROOT? Why it replaces variable with it's name?

**Comment by segiddins** [comment]
Xcodeproj doesn't currently handle build settings that are defined by xcodebuild (such as `SRCROOT`)

**Comment by ianbytchek** [comment]
@segiddins thanks for confirming. May I ask what would be the recommended approach in this case? Just manually replace `SRCROOT` or is there a better approach?
