### ISSUE TITLE
1.5.7 Broke Cocoapod lib create

### ISSUE THREAD

**Issue by tsukudabuddha** [CocoaPods/Xcodeproj#576]
<img width="583" alt="screen shot 2018-05-12 at 10 23 18 am" src="https://user-images.githubusercontent.com/10263083/39959965-bf0cd2f8-55ce-11e8-9fe1-d0e6a3fc206d.png">
This error occurs when trying to create new cocoapod lib. I installed 1.5.6 and was able to continue. Terminal output shows error with this file: lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb

**Comment by segiddins** [comment]
This is fixed on master
