### ISSUE TITLE
my xcodeproj version is 1.5.8, but I can't create lib with 'pod lib create'

### ISSUE THREAD

**Issue by Haisens** [CocoaPods/Xcodeproj#577]
$ pod lib create Test
Cloning `https://github.com/CocoaPods/pod-template.git` into `Test`.
Configuring Test template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - https://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )

What platform do you want to use?? [ iOS / macOS ]
 > iOS

What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > Yes

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

What is your class prefix?
 > T
/Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x007fdafd0e41a8> (NoMethodError)
Did you mean?  to_s
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/yinhaichao/Desktop/Test/setup/ProjectManipulator.rb:30:in `run'
	from /Users/yinhaichao/Desktop/Test/setup/ConfigureiOS.rb:73:in `perform'
	from /Users/yinhaichao/Desktop/Test/setup/ConfigureiOS.rb:7:in `perform'
	from /Users/yinhaichao/Desktop/Test/setup/TemplateConfigurator.rb:85:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

**Comment by dnkoutso** [comment]
Already fixed by https://github.com/CocoaPods/Xcodeproj/pull/573

**Comment by Haisens** [comment]
I test add require 'set',on build_settings_array_settings_by_object_version.rb.
```
module Xcodeproj
  class Project
    module Object
      class XCBuildConfiguration
        # yes, they are case-sensitive.
        # no, Xcode doesn't do this for other PathList settings nor other
        # settings ending in SEARCH_PATHS.
        module BuildSettingsArraySettingsByObjectVersion
        **require 'set'**
```

Is that right?

**Comment by dnkoutso** [comment]
sure if you want to apply it manually. Otherwise either use bundler or wait for the new release!

Going to close as fixed.
