### ISSUE TITLE
How to add Sticker Pack Extension to the Embedded Binaries section?

### ISSUE THREAD

**Issue by caojunxyz** [CocoaPods/Xcodeproj#584]
For CI purpose, I need to add "Sticker Pack Extension" to the Xcode project which is exported from Unity by script. 

The **Sticker Pack Extension** target is added successfully through the following script:

``` ruby
def add_stickers_extension(proj_dir_path="", proj_file_name="")
    proj_path = File::join(proj_dir_path, proj_file_name)
    project = Xcodeproj::Project.open(proj_path)
    puts "Project: #{project.path}"

    group = project.main_group.find_subpath('Stickers', true)
    group.new_reference("Stickers/Info.plist")
    assets = group.new_reference("Stickers/Stickers.xcassets")

    target = project.new_target(:sticker_pack, 'Stickers', :ios, "10.0")
    target.add_file_references([assets])
    target.build_configuration_list.set_setting('INFOPLIST_FILE', "Stickers/Info.plist")

    plist_path = File::join(proj_dir_path, "Stickers", "Info.plist")
     # the following two methods call do some customized configuration not relevant with the issue
    customize_plist(plist_path)
    customize_target(target)
    
    project.save
end
```
BUT,  the sticker target is not added to the app target's **Embedded Binaries** section. I tried several ways but all failed!  When manually add the **Sticker Pack Extension**, the app targets' "Embedded Binaries" section is correctly configured.

The **Sticker Pack Extension** is a kind of Application Extension:
![image](https://user-images.githubusercontent.com/15664171/42035752-456df720-7b16-11e8-83b6-14ba7451acdb.png)

The following pictures shows the settings and .pbxproj file diff between **empty Embedded Binaries section** and **manually add Sticker Pack Extension to Embedded Binaries section**

![image](https://user-images.githubusercontent.com/15664171/42035436-7f7930d4-7b15-11e8-98aa-2e754bf4979d.png)

![image](https://user-images.githubusercontent.com/15664171/42035458-8c162482-7b15-11e8-82a0-c6ea2c157ef7.png)

![image](https://user-images.githubusercontent.com/15664171/42035463-92abb280-7b15-11e8-8ea2-59511f49a255.png)

Thanks!

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by caojunxyz** [comment]
thanks for your suggestion
