### ISSUE TITLE
New Run Script build phase properties in Xcode 10

### ISSUE THREAD

**Issue by SlaunchaMan** [CocoaPods/Xcodeproj#587]
I don't see anything on here yet, so sorry if this is already posted, but Xcode 10 has some new attributes for a Run Script build phase: `inputFileListPaths` and `outputFileListPaths`. These allow you to specify which files the script uses, so that it doesn’t need to run when those files don’t change. More here: https://developer.apple.com/videos/play/wwdc2018/408/

When I run `pod install` on a project using Xcode 10, I get the following message:

```
[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

**Comment by amorde** [comment]
Hi @SlaunchaMan 

I believe this was implemented in https://github.com/CocoaPods/Xcodeproj/pull/579 - could you try it out with Bundler to see if it fixes the issue? I'm going to preemptively close this but will reopen if the fix doesn't work for your project.

**Comment by SlaunchaMan** [comment]
Yep, can confirm it’s fixed in `master`. Thanks!
