### ISSUE TITLE
Add Notification Service Extension target

### ISSUE THREAD

**Issue by solinder** [CocoaPods/Xcodeproj#589]
Hello.
Could you explain me please: is it possible to create Notification Service Extension target in my Xcode project using "xcodeproj"?
I saw the file /lib/xcodeproj/constants.rb and didn't find such constant in PRODUCT_TYPE_UTI.
Thanks.

**Comment by dnkoutso** [comment]
Don't know from the top of my head but it seems this might not be available and would require a PR to add support.

**Comment by keith** [comment]
You can, the type for this extension type in xcodeproj is `:app_extension` which is `com.apple.product-type.app-extension`

**Comment by amorde** [comment]
The constant is defined here:

https://github.com/CocoaPods/Xcodeproj/blob/e0089972ade7bfb30179dc04ad3026c3f4a74b7d/lib/xcodeproj/constants.rb#L158

Going to go ahead and close this as it looks to be supported but can re-open if there's something missing
