### ISSUE TITLE
Use Xcodeproj to create Xcode project file from .podspec

### ISSUE THREAD

**Issue by opfeffer** [CocoaPods/Xcodeproj#590]
This might not be the right place to ask but maybe someone has some helpful pointers for me...

I'm trying to use CocoaPods for some module-based development. As such I have a bunch of development pods I actively develop via my main project's workspace. When I add new files to a dev pod via the main project's workspace, the pod's own *.xcodeproj file does not get automatically updated.

I'm looking for a way to reliably re-generate the dev pods' .xcodeproj file using the information from the *.podspec file (`s.source_files` etc). Is this something CocoaPods/Xcodeproj can be helpful with? Or am I approaching this problem from an entirely wrong direction?

Appreciate any input! Thanks

**Comment by dnkoutso** [comment]
I think you want the recently open sourced https://github.com/square/cocoapods-generate
