### ISSUE TITLE
Add "inc" to HEADER_FILES_EXTENSIONS

### ISSUE THREAD

**Issue by mozeryansky** [CocoaPods/Xcodeproj#597]
We have created a podspec for a c++ project, but they use ".inc" for extensions to their header files. Can we either add ".inc" or make a way to specify additional extensions for headers.

Here's a relevant conversation: https://github.com/CocoaPods/CocoaPods/issues/3708

**Comment by mozeryansky** [comment]
I agree that the right solution would not be appending to that list, but to allow custom extensions. Common extensions should be in that list.

**Comment by mozeryansky** [comment]
Ha there already is a PR for adding ".cc"

https://github.com/CocoaPods/Xcodeproj/pull/514

**Comment by dnkoutso** [comment]
Seems like the `.cc` one went through a different path.

**Comment by mozeryansky** [comment]
".inc" was already added! https://github.com/CocoaPods/Xcodeproj/pull/598

**Comment by dnkoutso** [comment]
@mozeryansky I *just* did this in this PR? what do you mean?

**Comment by mozeryansky** [comment]
Oh, yes. Very fast. Thanks.
