### ISSUE TITLE
Push a new release

### ISSUE THREAD

**Issue by mozeryansky** [CocoaPods/Xcodeproj#599]
What is the schedule for releases? I noticed a change I want has been merged, but not in the latest release.

**Comment by dnkoutso** [comment]
This does not need to be tracked as an issue. You can still use this version by using https://bundler.io/v1.12/git.html

Sorry @mozeryansky going to close this.

We are looking to ship 1.6.0.beta.1 anyway so I don't think it will be long till we update this.

**Comment by mozeryansky** [comment]
Good to close, thanks for letting me know. And thanks for the quick replies!
