### ISSUE TITLE
The file reference can not be added into the Public?

### ISSUE THREAD

**Issue by Desgard** [CocoaPods/Xcodeproj#602]
I use the `Xcodeproj` to generate a xcode project in my work. And when I use the `phase.add_file_reference`, and the function can make the header reference into the **Project** default, and we can't control it.

<img width="760" alt="screen shot 2018-08-17 at 2 25 15 pm" src="https://user-images.githubusercontent.com/7804535/44251008-6c5a0d80-a229-11e8-9a3b-e778a9c1bf42.png">

Is there a API that can control it to be **Public** now?

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the Xcodeproj issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
