### ISSUE TITLE
"Xcodeproj doesn't know about the following attributes" in Xcode 10 GM

### ISSUE THREAD

**Issue by Wilsonator5000** [CocoaPods/Xcodeproj#608]
When running `pod install` in my project created with the Xcode 10 GM, I receive this warning in CocoaPods:

```
[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

I think this has to do with the `[CP] Check Pods Manifest.lock` build phase, as there are two new fields below it:
![screen shot 2018-09-15 at 4 53 49 pm](https://user-images.githubusercontent.com/12683684/45590519-f4eecb00-b907-11e8-85a1-25a4065fec4b.png)

**Comment by dnkoutso** [comment]
This has already been fixed. Can you update your xcodeproj gem?

**Comment by amorde** [comment]
Going to close as this is fixed in the latest release

**Comment by ramunasjurgilas** [comment]
I still getting this type of error.

I did update cocoapods to latest: 
```
[project](master)$ sudo gem install cocoapods
Password:
Successfully installed cocoapods-1.5.3
Parsing documentation for cocoapods-1.5.3
Done installing documentation for cocoapods after 2 seconds
1 gem installed
```

And after pod install getting error like shown on top:
```
[myproject](master)$ pod install
Analyzing dependencies
Downloading dependencies
... pods downloaded ...
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

Can someone assist regarding this error?

**Comment by amorde** [comment]
@ramunasjurgilas please update Xcodeproj with `gem update xcodeproj`

**Comment by cluelessoodles** [comment]
Also still getting this error - "Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new"

Like the previous poster, I also updated to 1.5.3 cocoapods `sudo gem install cocoapods`.

And when I tried to update Xcodeproj with `gem update xcodeproj` I get another error: 

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory

I changed the name of my Xcode project and am trying to reinstall pods and xcworkspace with pod install, but getting the above errors. Any ideas?
