### ISSUE TITLE
Convert document to old-style ASCII plist, if tool is available.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/Xcodeproj#61]
(Continuation of https://github.com/CocoaPods/CocoaPods/issues/926.)

When saving the document and @0xced’s [tool](https://github.com/0xced/xcodeproj) (which can save as the old-style ASCII plist by using Xcode’s private frameworks) is available, run that and convert it.

This is meant to make diffs in the Xcode projects nicer.

**Comment by fabb** [comment]
Is `xcproj` still relevant in recent cocoapods versions?

**Comment by orta** [comment]
no

**Comment by palcalde** [comment]
Guys, I'm having an issue now where every time I build my app the pbxproj gets converted to XML. 
I've tried installing xcodeproj with brew but doesn't solve the problem either. 

I'm using:
XCode 8.3
Cocoapods
/Users/pabloa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.1/lib/cocoapods.rb
XcodeProj
/Users/pabloa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.4/lib/xcodeproj.rb
XCproj
/usr/local/bin/xcpro

If I move a file around in the projec it recreates the pbxproj succesfully, but after compiling gets wrong again.

Any idea? Thank you!
