### ISSUE TITLE
how to add an app extension to my project ?

### ISSUE THREAD

**Issue by yishuiliunian** [CocoaPods/Xcodeproj#613]
i have found this way, but it not configure the host target. how to configure the host target?

~~~
xcodeproj.new_target(:app_extension, targetname, :ios, deployment_target)
~~~

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the Xcodeproj issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
