### ISSUE TITLE
the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa is generated by Xcode.

### ISSUE THREAD

**Issue by 13717943657** [CocoaPods/Xcodeproj#616]
the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa is generated by Xcode.

**Comment by amorde** [comment]
Dup of #362 - this was fixed in 1.6.0. Please update your Xcodeproj gem to get the fix.

**Comment by amorde** [comment]
Woops, looks like that's the wrong issue link. But here's the PR that fixed it https://github.com/CocoaPods/Xcodeproj/pull/579
