### ISSUE TITLE
Xcodeproj doesn't know about input/output file list paths for PBXShellScriptBuildPhase

### ISSUE THREAD

**Issue by actuallymrj** [CocoaPods/Xcodeproj#621]
[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

**Comment by dnkoutso** [comment]
Fixed and shipped already. Gem update xcodeproj.

**Comment by dnkoutso** [comment]
See https://github.com/CocoaPods/CocoaPods/issues/7835
