### ISSUE TITLE
Is it possible to specify UseModernBuildSystem - false?

### ISSUE THREAD

**Issue by johndpope** [CocoaPods/Xcodeproj#650]
related 
https://github.com/yonaskolb/XcodeGen/issues/470

 https://stackoverflow.com/questions/51205221/how-can-i-use-the-legacy-build-system-with-xcode-10s-xcodebuild

**Comment by dnkoutso** [comment]
I dont think support was added for this yet should be fairly easy to add so I believe.

**Comment by johndpope** [comment]
differing to https://github.com/tuist/xcodeproj/issues/358
