### ISSUE TITLE
Is it possible to have variables defined in configs to be expanded by default

### ISSUE THREAD

**Issue by jaredwy** [CocoaPods/Xcodeproj#654]
I have code similar to following code

```
 projects = file_references.collect { |x| Xcodeproj::Project.open(x.absolute_path(containing_dir))}     

projects[0].targets.each do |target|
    puts target.resolved_build_setting("LIBRARY_SEARCH_PATHS", true)
end
```
Which outputs 
```
{"Debug_x86_64"=>["$(COMMON_LIBRARY_PATHS)", "$(xxx_LIBRARY_PATH)", "$(xxx_xxx_LIBRARY_PATH)""], "Release_x86_64"=>["$(COMMON_LIBRARY_PATHS)", "$(xxx_LIBRARY_PATH)", "$(xxx_xxx_LIBRARY_PATH)"]} 
```

Is there a way to have those automatically resolve to things like `$(xxx_LIBRARY_PATH)` actual settings with out having to write a parser to look for $(*) and then use `common_resolved_build_setting` or `resolved_build_setting` to get their actual values? 

Or is it possible to get access to a `other_linker_flags`(on the config object) for an entire target?

**Comment by dnkoutso** [comment]
@jaredwy thanks for the question. This seems like a great StackOverflow question to ask under `xcodeproj` or `cocoapods` tag.

I do not know from the top of my head whether this is supported or not.

**Comment by jaredwy** [comment]
Ah! Shall also ask there. Wasn't sure the best way to reach the team :) 

Thanks for info.
