### ISSUE TITLE
Xcodeproj doesn't know about the following attributes

### ISSUE THREAD

**Issue by Hovo-Infinity** [CocoaPods/Xcodeproj#659]
` Xcodeproj doesn't know about the following attributes`
 {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

**Comment by dnkoutso** [comment]
Duplicate issue and has already been fixed. Please use `gem update xcodeproj`.
