### ISSUE TITLE
How to create a Script build rule

### ISSUE THREAD

**Issue by pepone** [CocoaPods/Xcodeproj#667]
How can I add a new Script build rule to a target, is there any samples?

**Comment by dnkoutso** [comment]
Start here https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/project/object/native_target.rb#L297

it's also best to ask these questions in StackOverflow since this does not appear to be an issue with the library itself.

**Comment by pepone** [comment]
Thanks @dnkoutso , I was looking for build rules not build phase, I will ask in StackOverflow

**Comment by stackJolin** [comment]
how to upgrade the level, so that the new shell is run before compile source files
@dnkoutso

**Comment by stackJolin** [comment]
this is the result that invoke "new_shell_script_build_phase"
![image](https://user-images.githubusercontent.com/14361098/61717292-60f55780-ad93-11e9-9adc-5656ab9036e9.png)

but，how can I get the result on below
![image](https://user-images.githubusercontent.com/14361098/61717437-a0bc3f00-ad93-11e9-8b03-bf5e985d9e8d.png)
