### ISSUE TITLE
Can I rename a group?

### ISSUE THREAD

**Issue by ripperhe** [CocoaPods/Xcodeproj#670]
Can I rename a group? Or can I change the order of groups?
Please help me!  😘

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
