### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2472905357** [CocoaPods/Xcodeproj#674]
pod install的时候报错[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-GKDYVideo/Pods-GKDYVideo-frameworks-${CONFIGURATION}-input-files.xcfilelist"], "outputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-GKDYVideo/Pods-GKDYVideo-frameworks-${CONFIGURATION}-output-files.xcfilelist"]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

**Comment by dnkoutso** [comment]
`gem update xcodeproj`
