### ISSUE TITLE
Capabilities App-Group

### ISSUE THREAD

**Issue by embassem** [CocoaPods/Xcodeproj#679]
is there a way to change app-Group to different Values and make it selected.

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
