### ISSUE TITLE
Can't get `pod update` to work on macOS Catalina

### ISSUE THREAD

**Issue by jefhai** [CocoaPods/Xcodeproj#688]
Can't get `pod update` to work on macOS Catalina 
```
JeffMacbookPro:Proj-iOS jefhai$ pod update

[!] Invalid `Podfile` file: [Xcodeproj] Unknown object version..

 #  from /Users/jefhai/Documents/git/Proj-iOS/Podfile:24
 #  -------------------------------------------
 #  
 >  project = Xcodeproj::Project.open "Proj.xcodeproj"
 #  project.targets.each do |t|
 #  -------------------------------------------

[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXBuildFile' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

**Comment by dnkoutso** [comment]
Do you have the sample .xcodeproj you are using and this fails with?

**Comment by jefhai** [comment]
Unfortunately I can't provide the project file I'm working with. But if I take my Xcode 10 project, run pod install with cocoapods 1.7.1 it runs successfully- then when I open Xcode 11 beta and run pod install with the IDE open I see that error.

**Comment by dnkoutso** [comment]
What is the file or reference that includes `{"platformFilter"=>"ios"}` in your project.pbxproj?

Did you use SPM?

**Comment by jefhai** [comment]
`2F206422203BBD3B00B1D4EF /* OpenGLES.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 7EB9A0FB17C3200300817692 /* OpenGLES.framework */; platformFilter = ios; };`

I figure OpenGLES is no longer supported. Only reference I have for it in the project.pbxproj

But would cocoapods/Xcodeproj know that? 

Not sure what SPM is. So no I think?

**Comment by dnkoutso** [comment]
Will investigate

**Comment by dnkoutso** [comment]
Its taken care of here https://github.com/CocoaPods/Xcodeproj/pull/687

**Comment by Coeur** [comment]
> Not sure what SPM is.

Swift Packet Manager, especially regarding the new Xcode 11 integration in this context.

**Comment by rajat1812** [comment]
getting error o pod init or pod update.

Rajats-MacBook-Pro: bmr rajatbhalla$ pod init
-bash: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by jefhai** [comment]
@rajat1812 have you tried reinstalling that version of ruby?

**Comment by rajathk** [comment]
Try this-
sudo gem install cocoapods

**Comment by rajat1812** [comment]
Yup now its resolved thank you

**Comment by alvarezac1** [comment]
Has anyone had issues with getting the error `No such module` ? I followed the steps above to install cocoapods with Catalina but still having issues importing the pod.

![image](https://user-images.githubusercontent.com/56129207/66850026-d2751a00-ef2c-11e9-9bcc-cfe37558b2d7.png)

**Comment by jefhai** [comment]
I’ve had this issue before. But it seamed intermittent.. Resolved hours later.. I was using StarScream

**Comment by alvarezac1** [comment]
@jefhai is there anyway you checked the version of cocoapods? I'm using 1.8.3. Is there anything you added to your podfile specifically?

**Comment by jefhai** [comment]
No, It was working before and then it was not. I was getting an error similar to yours. And then it resolved itself.

**Comment by alvarezac1** [comment]
I'm hoping to compare the setups we both have. What version of cocoapods are you using? You can find out by typing `pod --version` in your Terminal

**Comment by jefhai** [comment]
I have 1.8.1

**Comment by paulb777** [comment]
Try building to seed the Xcode module map.

**Comment by pratik1994** [comment]
Please make sure u di not forget this line: XCode > Preferences > Locations > Command Line Tools > XCode 11.X.X and then run sudo gem install -n /usr/local/bin cocoapods
