### ISSUE TITLE
Xcode project delete a specified scheme

### ISSUE THREAD

**Issue by huakucha** [CocoaPods/Xcodeproj#708]
'pod install' help me create a scheme in Pods.xcodeproj,but my main project already have a same name scheme,I want to delete a specified scheme in Pods.xcodeproj ,xcodebuild will find the first one,but it's not i want,how can i do ? Can Xcodeproj do it?

**Comment by dnkoutso** [comment]
You can delete the scheme in `post_install` hook.

You can easily do it this outside of Xcodeproj. 

Going to close as this is not an issue and it's more of a question. Please also ask in StackOverflow under `cocoapods` tag.

**Comment by wtmoose** [comment]
Hi @dnkoutso. I've asked on StackOverflow as you suggested and got no responses. It would be awesome if someone here could chime in with an answer or clue.

https://stackoverflow.com/questions/67796339/how-to-delete-a-scheme-in-cocoapods-post-install-hook
