### ISSUE TITLE
Option `--project` suggested erroneously

### ISSUE THREAD

**Issue by KyLeggiero** [CocoaPods/Xcodeproj#709]
It suggests that I use the `--project` option, and then says that option is unknown

```plain
% xcodeproj config-dump
[!] No Xcode project document found in the current working directory. Please specify which to use with the `--project` option.

✘ % xcodeproj config-dump --project Foobar.xcodeproj 
[!] Unknown option: `--project`
Did you mean: --verbose?
```

**Comment by segiddins** [comment]
That message should be updated, try passing the project as the first arg to `config-dump` ?

**Comment by BenLeggiero** [comment]
That worked, thanks. It does still need to be updated. This ticket can be used for tracking that message update.
