### ISSUE TITLE
Are there any examples of adding objects to the project?

### ISSUE THREAD

**Issue by David-A-RogersHS2** [CocoaPods/Xcodeproj#711]
For instance, I would like to programmatically add a new build configuration based on an existing one (like you'd do interactively in Xcode > Project settings > Info). Since uuid is read-only for objects, I assume there is some other way to create a valid XCBuildConfiguration. But I don't see one in the api documentation.

If there is other documentation feel free to point me in that direction.

**Comment by M1ke** [comment]
Did you manage to fix this?
