### ISSUE TITLE
Documentation link seems to be broken

### ISSUE THREAD

**Issue by ACoolmanBigHealth** [CocoaPods/Xcodeproj#717]
https://www.rubydoc.info/gems/xcodeproj just shows:
```
Processing xcodeproj
xcodeproj (1.12.0) is being processed. You'll be redirected when the pages are built, it shouldn't take much longer.
```

**Comment by dnkoutso** [comment]
Same happens for other gems too like https://www.rubydoc.info/gems/bundler or https://www.rubydoc.info/gems/cocoapods.

Either way there isn't much we can do from here as we do not own rubydoc.info.

Going to close for now.
