### ISSUE TITLE
Can't get to the api documentation (http://www.rubydoc.info/gems/xcodeproj)

### ISSUE THREAD

**Issue by David-A-RogersHS2** [CocoaPods/Xcodeproj#718]
When I try to get to the Xcodeproj api documentation from the main GitHub page, I get a processing Xcodeproj message the never (10-15 minutes) goes away.

**Comment by amorde** [comment]
Hi there!

Looks like it's up now? https://www.rubydoc.info/gems/xcodeproj

Going to close as this doesn't seem to be an issue. Thanks!
