### ISSUE TITLE
Missing Attributes with run Script phase

### ISSUE THREAD

**Issue by olbrichj** [CocoaPods/Xcodeproj#732]
Errormessage: [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>["$(SRCROOT)/input.xcfilelist"], "outputFileListPaths"=>["$(SRCROOT)/output.xcfilelist"]} for the 'PBXShellScriptBuildPhase' isa.

To reproduce:
Create a project and add a dependency via Carthage to the testtarget. This requires to add a "run script phase" and input/output.xcfilelists (see: https://github.com/Carthage/Carthage)
To reproduce this problem, you don't even have to add values to these phases. Leaving them empty results in the same error just with [] instead of the files needed.

Version: Xcode 11.2.1

**Comment by amorde** [comment]
This was fixed in https://github.com/CocoaPods/Xcodeproj/pull/579 - please update to the latest version of Xcodeproj 👍
