### ISSUE TITLE
Planned date for 1.15.0 release

### ISSUE THREAD

**Issue by revolter** [CocoaPods/Xcodeproj#733]
Is the 1.15.0 release planned for a specific date / period?

**Comment by dnkoutso** [comment]
Not currently. We do not follow a release schedule given that all of this work happens on the spare time of folks.

If you need to use master you can easily do so by using Bundler https://bundler.io/

**Comment by revolter** [comment]
Understood, but I need a new release to update it in CocoaPods's gemspec file:

https://github.com/CocoaPods/CocoaPods/blob/42741d897eb8ab34f9a1524988f59ff3f7760cc4/cocoapods.gemspec#L41

**Comment by dnkoutso** [comment]
hmm why do you need a release? The gem version of Xcodeproj on master is 1.14.0 (https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/gem_version.rb).

Use a `Gemfile` with:
```ruby
source 'https://rubygems.org' do
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git', :ref => 'the-commit-sha-here'
gem 'cocoapods
```

Run `bundle install` and then `bundle exec pod install` etc...

**Comment by dnkoutso** [comment]
I mean we will most likely have a release soon but I am only saying there is no timeframe for when specifically.

**Comment by revolter** [comment]
Oh, so even if the `cocoapods` gem references `1.14.0`, if I explicitly reference `xcodeproj` with a specific commit, it will use that one?

**Comment by dnkoutso** [comment]
yes it should be ok because the commit you will use from `master` still has 1.14.0 as the version in the gemspec of xcodeproj.

Furthermore even if `master` had 1.15.0 (which we should probably always do as part of our release process) it would _still_ work because cocoapods requirement is `'>= 1.14.0', '< 2.0'` which means 1.15.0 would satisfy that requirement.

**Comment by dnkoutso** [comment]
Going to close as no further action is needed here besides us releasing a new version which should happen soon.

We can continue discussion on the closed ticket!

**Comment by revolter** [comment]
Got it, thanks! 😃
