### ISSUE TITLE
remove_from_project is not working for target

### ISSUE THREAD

**Issue by felire** [CocoaPods/Xcodeproj#750]
Hi, I want to build a script to remove some targets in my project, but it's not working. Here is my code:

```
require 'xcodeproj'
project_path = './ios/UltimaPrueba.xcodeproj'
project = Xcodeproj::Project.open(project_path)

project.targets.each do |target|
 if target.name != 'UltimaPrueba'
  target.remove_from_project
 end
end
```
The script run fine but nothing happen, my Xcode project is the same after running the script. 

My Xcode version is: 11.1

**Comment by dnkoutso** [comment]
Did you call `project.save`?

**Comment by felire** [comment]
Thanks! In fact, it was that. But now i've realized that i have another problem. It deletes all the targets I want to delete except one, the target 'UltimaPrueba-tvOS' is not being deleted.

PD: You should add the info of the project.save in the README, the doc is a bit confusing I think

**Comment by felire** [comment]
It's a bit weird, if I execute the script twice the target is deleted. And if I execute the script once but 
I go through the list deleting target twice, the target is also deleted

**Comment by dnkoutso** [comment]
> It deletes all the targets I want to delete except one, the target 'UltimaPrueba-tvOS' is not being deleted.

Print out the `target.name` on each iteration and see the names.

I am going to close this one as I do not see a bug here or enhancement yet. I will re-open it though if we continue the discussion and find something to improve or fix.

**Comment by JulianKingman** [comment]
I encountered the same issue, if I run through the list twice and delete it works. It's like `remove_from_project` has the wrong target, or can't execute once the first one executed (maybe the pointer gets destroyed?). Anyway, happy to have the workaround, thanks @felire
