### ISSUE TITLE
Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.

### ISSUE THREAD

**Issue by ayon-affle** [CocoaPods/Xcodeproj#755]
Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-VizurySwiftSample/Pods-VizurySwiftSample-frameworks-${CONFIGURATION}-input-files.xcfilelist"], "outputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-VizurySwiftSample/Pods-VizurySwiftSample-frameworks-${CONFIGURATION}-output-files.xcfilelist"]} for the 'PBXShellScriptBuildPhase' isa.

**Comment by dnkoutso** [comment]
`gem update xcodeproj` already fixed.
