### ISSUE TITLE
xcconfig doesn't support multiple `-filelist` ld flags

### ISSUE THREAD

**Issue by RyanLeeLY** [CocoaPods/Xcodeproj#770]
My xcconfig file is just like below:
```
...
OTHER_LDFLAGS=$(inherited) -ObjC -filelist xxx/xxx/xxx -filelist yyy/yyy/yyyy
...
```

I use xcodeproj/config to read this file and the output string will be:
```
...
OTHER_LDFLAGS=$(inherited) -ObjC -filelist xxx/xxx/xxx  yyy/yyy/yyyy
...
```
the -filelist flags will be merged because of the internal data structure is `Set`.

**Comment by dnkoutso** [comment]
You can specify a file for `OTHER_LDFLAGS` using @/path/to/file
