### ISSUE TITLE
Not able to access known_regions 

### ISSUE THREAD

**Issue by sujata23** [CocoaPods/Xcodeproj#779]
Hi Team,

I am trying to access known_regions using following code:- 
    ```

```
> project_path = 'abcd.xcodeproj'
>     project = Xcodeproj::Project.open(project_path)
>     project.known_regions.each do |region|
>       puts(region)
>     end
>    end
```

```

The above code showing following error :- 
`"undefined method `known_regions' for #<Xcodeproj::Project>"`
Can any one please suggest

**Comment by dnkoutso** [comment]
Can you use `project.root_object.known_regions`?

**Comment by sujata23** [comment]
Thanks @dnkoutso , it works
