### ISSUE TITLE
AbstractTarget only listing the sub-project dependencies and not all dependencies.

### ISSUE THREAD

**Issue by krishnaagarwal1994** [CocoaPods/Xcodeproj#808]
I have project A with project B and c as subprojects.
Project A contains the target TA1, TA2, TA3... 
TA1 depends13 on TA2, TA3, and some targets present in project C and C

when doing
`TA.dependencies`
The output is only listing dependencies/targets that are present in project B and C, and not listing the dependencies from project A.

please help with this.
Thanks.

**Comment by krishnaagarwal1994** [comment]
So looks like the name attribute on PBXTargetDependency is only accessible for sub-project targets.
Whereas the display_name method returns the name for all targets including project and subprojects.
Sorry for the trouble, since I got the fix, I am closing this issue now.
Thank you.

**Comment by MikeFighting** [comment]
Do you know how to add a subproject for a project ? I got this issue when I want to add a target dependence from different project:
`Uncaught exception: add_dependency received target that belongs to a project that is not this project and is not a subproject of this project`
