### ISSUE TITLE
Add SWP packages to existing project

### ISSUE THREAD

**Issue by cianiandreadev** [CocoaPods/Xcodeproj#815]
Hi all,

I have a question about the usage of the tool:
I have an xcode project (ios) where I need to dynamically add swift packages using Xcodeproj trough command line.
I saw that you have `XCSwiftPackageProductDependency` and `XCRemoteSwiftPackageReference` but I couldn't find out how to use them.
For example, how is possible to specify which version to use? How to add to an existing project?
Sorry if it may sounds a stupid question but I'm quite new to Xcodeproj.

Thanks

**Comment by igor-makarov** [comment]
@cianiandreadev - Xcodeproj is intended to be used as a lower-level library for use in CocoaPods and other projects.

If you want to just add SwiftPM packages to Xcode, check out [Xcoed](https://github.com/igor-makarov/xcoed) - a CLI tool I made exactly for this.

**Comment by cianiandreadev** [comment]
@igor-makarov thanks a lot!
I will check that out!
