### ISSUE TITLE
Q: Compare 2 targets

### ISSUE THREAD

**Issue by MarkyAli** [CocoaPods/Xcodeproj#817]
Hi,
I use this script to compare 2 targets.
https://github.com/smirn0v/xcode-same-targets
it was probably caused by the new xcode.

There was a problem recently. The script stopped working.
Is there a way to compare 2 targets using Xcodeproj?

I need to stop building if the targets don't match.
At the same time, I want to add an exception to some files.

**Comment by dnkoutso** [comment]
I dont think this is supported at this time.

**Comment by dnkoutso** [comment]
Try `project diff`?
