### ISSUE TITLE
[!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["8C16436754324772B7FB1D5E", "62BAAFD4F5354A03AFCE0F62"]} for the 'PBXProject' isa.

### ISSUE THREAD

**Issue by Lllong** [CocoaPods/Xcodeproj#819]
when i add a xxx.xcodeproj to yyyy.xcodeproj

**Comment by Lllong** [comment]
MB0 TestCreateProject % ruby generate_ios_flutter_proj.rb
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
/Users/xxxxxx/Desktop/TestCreateProject/generate_ios_flutter_proj.rb
[!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["8C16436754324772B7FB1D5E", "62BAAFD4F5354A03AFCE0F62"]} for the 'PBXProject' isa.

**Comment by Lllong** [comment]
project = Xcodeproj::Project.open(project_path)

group = project.main_group.find_subpath(File.join('TestCreateProject'), true)

file_ref = group.new_reference('../../ios/xxxxxx.xcodeproj')

**Comment by Lllong** [comment]
xxx.xcodeproj project is generated by CMake, not by XCode.

**Comment by dnkoutso** [comment]
Please upload a sample project demonstrating the issue.
