### ISSUE TITLE
Xcode 13 beta introduced new Project Format (13.0)

### ISSUE THREAD

**Issue by lpusok** [CocoaPods/Xcodeproj#821]
Info.plist and entitlements plist (*.emtitlements) is no longer included by default in a newly created project. Unsure if there are other changes.

Error message:
```[Xcodeproj] Unknown object version.```

**Comment by dnkoutso** [comment]
The `Unknown object version` is fixed here https://github.com/CocoaPods/Xcodeproj/pull/825
