### ISSUE TITLE
Cocoapods issue after Xcode 12 upgrade

### ISSUE THREAD

**Issue by Dev1bar1clay1s** [CocoaPods/Xcodeproj#822]
We have recently upgraded the Xcode from 11 to 12.4. And now we are facing below mentioned build time issues. The project was working fine till Xcode 11. We are kind of stuck here tried upgrading the cocoapods version but nothing working

MDTextAccessibility 
- Redefinition of module 'libxml2' 
- Could not build module 'CoreFoundation' ...... etc

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
