### ISSUE TITLE
planned date for 1.20.0 release

### ISSUE THREAD

**Issue by charleyzhuyi** [CocoaPods/Xcodeproj#823]
Hi,

I have been 8 months since the last release of 1.19.0, may I know when do you plan to release 1.20.0? 
 since cocoapods is depends on the latest release of X codeproj in [here](https://github.com/CocoaPods/CocoaPods/blob/42741d897eb8ab34f9a1524988f59ff3f7760cc4/cocoapods.gemspec#L41) and our internal build system prevent us to use any non-public release version of cocoapods and/or Xcodeproj, we won't able to use the new feature introduced after 1.19.0 (e.g. scheme/execution_action.rb)

Thank you!

**Comment by dnkoutso** [comment]
Will do one this week!
