### ISSUE TITLE
Xcodeproj doesn't know platformFilters

### ISSUE THREAD

**Issue by mangerlahn** [CocoaPods/Xcodeproj#838]
In my multi-platform project Xcodeproj emits the following warning: 

`[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilters"=>["macos"]} for the 'PBXBuildFile' isa.`

**Comment by dnkoutso** [comment]
can you provide an xcode project that shows this warning?

**Comment by mangerlahn** [comment]
[Testapp.zip](https://github.com/CocoaPods/Xcodeproj/files/6838523/Testapp.zip)

Sure! Sorry for the lack of information here. The structure is as follows: We have an app that uses multiple frameworks. We are currently converting these frameworks to be cross-platform for macOS and iOS. In Xcode 13 there is a new UI to specify platform filters. We use this to define whether a file should be included for all platforms. 

![Screenshot 2021-07-19 at 08 43 40](https://user-images.githubusercontent.com/11056766/126114656-91064d08-7703-4dd0-b42b-5dafd60b05a5.png)

**Comment by dnkoutso** [comment]
awesome thanks, i think we can fix that easily.

**Comment by dnkoutso** [comment]
PR https://github.com/CocoaPods/Xcodeproj/pull/841
