### ISSUE TITLE
How to use Xcodeproj auto  create Xcode project file from .podspec 

### ISSUE THREAD

**Issue by wulongwang** [CocoaPods/Xcodeproj#840]
Xcodeproj can do it?

**Comment by igor-makarov** [comment]
There's `app_spec` if you want it through a podspec - although it's not very well documented and seem to be limited.

If you want a whole app project with fully customizable DSL, check out https://github.com/igor-makarov/xcake

**Comment by dnkoutso** [comment]
Look into this as well https://github.com/square/cocoapods-generate
