### ISSUE TITLE
Is it possible to add a target from a subproject as a dependency in root project?

### ISSUE THREAD

**Issue by nangalvivek** [CocoaPods/Xcodeproj#849]
Pretty much what the title says. Even if I add a couple of targets as dependencies using xcode, `PBXTargetDependency.target` is `nil` and `PBXTargetDependency. container_portal` does not provide a way to get to the `PBXNativeTarget`.

**Comment by dnkoutso** [comment]
do you have a sample project for me to inspect and understand?

**Comment by nangalvivek** [comment]
<img width="600" alt="Screenshot 2021-07-30 at 6 05 49 PM" src="https://user-images.githubusercontent.com/5489587/127653971-07439456-c54c-4f6a-b0e1-5cecb4a4bb12.png">
I need to discover all targets in the subprojects of the project titled 'Root' in the screenshot and add them as its dependencies. You can download the sample project from [here](https://github.com/CocoaPods/Xcodeproj/files/6907545/Root.zip).
