### ISSUE TITLE
Xcodeproj crashing on subprojects

### ISSUE THREAD

**Issue by avetiso** [CocoaPods/Xcodeproj#850]
Hello everyone,

We use this project as part of our mobile development at MX Technologies. Changing settings in the xcode project file, adding source files, etc. all lead to crashes with our subprojects. Are there any plans to fix this anytime soon?

We just want to know if we can expect any fix for this problem eventually, otherwise we will probably fork our own copy internally as we do not have any concerns with breaking functionality for anyone other than for our own team. We've been keeping an eye on PR's that have gone up to get this fixed, but have noticed that they are not being merged in.

If anyone knows the answer to this and can get back to us, it would be much appreciated. Thank you!

**Comment by dnkoutso** [comment]
Lets continue discussion here https://github.com/CocoaPods/Xcodeproj/pull/762
