### ISSUE TITLE
Not support the recognition of MacCatalyst flag

### ISSUE THREAD

**Issue by xuzhongping** [CocoaPods/Xcodeproj#868]
Hi,is it possible to increase the recognition of items that support maccatalyst?

**Comment by dnkoutso** [comment]
Sorry I cannot understand what you mean?

**Comment by xuzhongping** [comment]
@dnkoutso  Sorry,when I read the code, I found that it is supported, but there does not seem to be a public interface to mean whether a target supports catalyst?
