### ISSUE TITLE
Update coming?

### ISSUE THREAD

**Issue by jsorge** [CocoaPods/Xcodeproj#918]
The last release of the gem was over a year ago, and while there has been little activity there has been _some_ activity that remains unreleased in a gem update. When will a new version be released?

**Comment by orta** [comment]
Likely when the new Xcode releases, there'll be a new CocoaPods release

**Comment by jsorge** [comment]
Ah so are releases of this gem tied to CocoaPods releases?

**Comment by orta** [comment]
No, but effectively, yes

**Comment by megabitsenmzq** [comment]
iOS17 is about to be released. I still waiting for this to support object version 60.

**Comment by appfrilans** [comment]
Same issue here with Xcode 15!

[!] Xcodeproj doesn't know about the following attributes {"expectedSignature"=>"AppleDeveloperProgram:Y28TxxxSHX7:Stripe Inc"} for the 'PBXFileReference' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

**Comment by ahammerpg** [comment]
As [fastlane](https://github.com/fastlane/fastlane) has a dependency to this gem, our fastlane builds on the CI are currently broken when using the Xcode 15 project format. A workaround for now is to revert to previous project formats.

**Comment by megabitsenmzq** [comment]
Same here.

> As [fastlane](https://github.com/fastlane/fastlane) has a dependency to this gem, our fastlane builds on the CI are currently broken when using the Xcode 15 project format. A workaround for now is to revert to previous project formats.

**Comment by jcesarmobile** [comment]
Maybe it's not released because we didn't ask nicely, so going to try again.

Can you please do a release of Xcodeproj and then of CocoaPods?
Please, please, please.

**Comment by appfrilans** [comment]
I agree on that one. 1000 times please!

**Comment by brian-telintelo-kr** [comment]
@dnkoutso Any chance you could tag a release that includes your Xcode 15 changes

**Comment by dnkoutso** [comment]
Shipped 1.23.0 of Xcodeproj.

**Comment by dnkoutso** [comment]
https://github.com/CocoaPods/Xcodeproj/releases/tag/1.23.0
