### ISSUE TITLE
Xcode 15.3 Compatibility

### ISSUE THREAD

**Issue by Brett-Best** [CocoaPods/Xcodeproj#933]
Xcode 15.3 introduces:
- object version 63
- new property attributes {"minimizedProjectReferenceProxies"=>"1"} for the 'PBXProject' isa

**Comment by wojciech-kulik** [comment]
I noticed also another problem. When Xcode 15.3 is opened and I do any changes to the project using `Xcodeproj`. The `App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` gets deleted every time.

If I do the same with closed Xcode and open it after changes, it's fine. It also works correctly with Xcode 15.2.

**Comment by wojciech-kulik** [comment]
It turns out that most likely it's not a Xcodeproj-related bug. Whenever you change `xcodeproj` outside of Xcode when it's opened, this issue occurs.

**Comment by Whirlwind** [comment]
@amorde Could you have a look this issue?
