### ISSUE TITLE
Issue while initializing the pod file in xcode 16

### ISSUE THREAD

**Issue by gtdev6** [CocoaPods/Xcodeproj#962]
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["184DDBB42C9C427900B06A93"], "path"=>"Social", "sourceTree"=>"<group>"}`

**Comment by Italo-J-A-Fernandes** [comment]
@gtdev6 How was it resolved?

**Comment by gtdev6** [comment]
Here the solution that worked for me: right click projectname.xcodeproj file and select Show Package Contents you can see the file project.pbxproj and open with texteditor 
Remove the following lines in this file 
minimizedProjectReferenceProxies = 1; 
preferredProjectObjectVersion = 77; 
Also update the below version objectVersion = 77; 
to objectVersion = 56;

**Comment by JOsacky** [comment]
> Here the solution that worked for me: right click projectname.xcodeproj file and select Show Package Contents you can see the file project.pbxproj and open with texteditor Remove the following lines in this file minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77; Also update the below version objectVersion = 77; to objectVersion = 56;

This seems like a workaround, not a solution. It would be nice if we supported objectVersion = 77 so that we won't need this workaround as people update
