### ISSUE TITLE
CocoaPods pod init Fails with “Unknown ISA PBXFileSystemSynchronizedRootGroup” Error on Xcode 16

### ISSUE THREAD

**Issue by kundancodelab** [CocoaPods/Xcodeproj#963]
showing error after running  pod init command  if it is  then not able to see project.xcworkspace file  even after  firing up pod install command.

**Comment by JonnyBeeGod** [comment]
I think this has something to do with Xcode 16 new feature "buildable folders" which gets rid of the project file references for files

**Comment by amorde** [comment]
This is fixed by https://github.com/CocoaPods/Xcodeproj/pull/985 and shipped in [1.26.0](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0)
