### ISSUE TITLE
Doesn’t support the new Xcode 16 folders format

### ISSUE THREAD

**Issue by sborovikov-belkacar** [CocoaPods/Xcodeproj#969]
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
[14:52:02]: Called from Fastfile at line 103
[14:52:02]: ```
[14:52:02]:     101:	    match_dev
[14:52:02]:     102:	
[14:52:02]:  => 103:	    update_code_signing_settings(
[14:52:02]:     104:	      targets:[APP_TARGET[:app_target]], 
[14:52:02]:     105:	      use_automatic_signing: false, 
[14:52:02]: ```
[14:52:02]: `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["ECD642032CA44CD6006063AE"], "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"BelkaCar", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
+-----------------------------------------------------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | default_platform                     | 0           |
| 2    | is_ci                                | 0           |
| 3    | xcodes                               | 0           |
| 4    | Switch to ios fastlane_keychain lane | 0           |
| 5    | create_keychain                      | 0           |
| 6    | Switch to ios match_dev lane         | 0           |
| 7    | match                                | 3           |
| 💥   | update_code_signing_settings         | 0           |
+------+--------------------------------------+-------------+
+-------------------------------------------+
|         Plugin updates available          |
+-----------+--------------+----------------+
| Plugin    | Your Version | Latest Version |
+-----------+--------------+----------------+
| appcenter | 2.0.0        | 2.1.2          |
+-----------+--------------+----------------+
[14:52:02]: To update all plugins, just run
[14:52:02]: $ bundle exec fastlane update_plugins
[14:52:02]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
bundler: failed to load command: fastlane (/opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane)
/opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid': \e[31m[!] `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["ECD642032CA44CD6006063AE"], "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"BelkaCar", "sourceTree"=>"<group>"}` (RuntimeError)
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new\e[0m
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:113:in `open'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/actions/update_code_signing_settings.rb:10:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:[229](https://github.com/belka-car/ios-mobile-app/actions/runs/11108635596/job/30862042174#step:4:230):in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:103:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli.rb:455:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli.rb:35:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli.rb:29:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/exe/bundle:28:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/exe/bundle:20:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:268:in `new_from_plist': uninitialized constant Xcodeproj::Project::Object::PBXFileSystemSynchronizedRootGroup (NameError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:113:in `open'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/actions/update_code_signing_settings.rb:10:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:[255](https://github.com/belka-car/ios-mobile-app/actions/runs/11108635596/job/30862042174#step:4:256):in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:103:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.223.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli.rb:455:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli.rb:35:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/cli.rb:29:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/exe/bundle:28:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.20/exe/bundle:20:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
Error: Error: Executing lane fastlane build_debug_app app_target:belka failed.
Error: Executing lane fastlane build_debug_app app_target:belka failed.

**Comment by amorde** [comment]
This is fixed by https://github.com/CocoaPods/Xcodeproj/pull/985 and shipped in [1.26.0](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0)
