### ISSUE TITLE
Xcode 16 Error attributes {"exceptions"=>["CE6990CC2CC67A3A0068587B"], "explicitFileTypes"=>{}, "explicitFolders"=>[]} for the 'PBXGroup' isa.

### ISSUE THREAD

**Issue by zenzero3** [CocoaPods/Xcodeproj#982]
I just try solving  error xccode isa with PBXGROUP  but have warning this [!] [!] Xcodeproj doesn't know about the following attributes {"exceptions"=>["CE6990CC2CC67A3A0068587B"], "explicitFileTypes"=>{}, "explicitFolders"=>[]} for the 'PBXGroup' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

**Comment by amorde** [comment]
This is fixed by https://github.com/CocoaPods/Xcodeproj/pull/985 and shipped in [1.26.0](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0)
