### ISSUE TITLE
[1.26.0] misconfigure some Pod build settings

### ISSUE THREAD

**Issue by ParryingDagger** [CocoaPods/Xcodeproj#990]
Hi, I'm using Xcode15.2. After updating to 1.26.0, I found that some build settings of pods are changed.

`ENABLE_USER_SCRIPT_SANDBOXING` and `ENABLE_MODULE_VERIFIER` was set to YES.

`Supported Languages` and `Supported Languages Dialects` used to be empty. Now they are set.

I have too many pods cannot be compiled with those settings.

<img width="377" alt="WeChatWorkScreenshot_4a7ac772-c642-4cd3-a12f-3e67cd0296f4" src="https://github.com/user-attachments/assets/0b23a89f-bc46-4a9a-86bd-c741b294bbae">

<img width="640" alt="WeCom20241028-211702@2x" src="https://github.com/user-attachments/assets/05f70804-779e-43f4-86bc-6edfaa1df93c">

I have locked version of xcodeproj to a lower one to resolve this problem.

I found this version is meant to support xcode16. Is it possible to be compatible with Xcode15?

**Comment by TomaszPilarski** [comment]
I have the same issue and in my case the issue happens in both Xcode versions, 15.4 and 16.

**Comment by Alger** [comment]
I have the same issue on my project with Xcode version 15.x and 16 too

**Comment by ynyyn** [comment]
FYI: This change has been reverted, released in 1.27.0.
https://github.com/CocoaPods/Xcodeproj/pull/992
https://github.com/CocoaPods/Xcodeproj/releases/tag/1.27.0

**Comment by ParryingDagger** [comment]
@ynyyn Thanks. I have tried 1.27.0. It worked.
